### ISSUE TITLE
Existing view beans are never picked up.

### ISSUE THREAD

**Issue by mmoayyed** [thymeleaf/thymeleaf-spring#102]
I have the following:

```
    @Bean(name="responseView")
    public ThymeleafView responseView() {
        final ProtocolView view = new ProtocolView ("/protocol/responseView");
        view.setBeanName("responseView");
        return view;
    }

    public static class ProtocolView extends ThymeleafView {
        ProtocolView(final String templateName) {
            super(templateName);
        }
    }
```

If I attempt to route the flow to `responseView`, the resolver never picks up my existing bean. It always wants to set the template name to the view name passed which is `responseView`, rather than using the existing bean to pick up the configured template name. 

This is in 2.1.4, latest of Spring 4.

**Comment by mmoayyed** [comment]
In the resolver:

``` java
        AbstractThymeleafView view = BeanUtils.instantiateClass(getViewClass());

        final boolean viewBeanExists = beanFactory.containsBean(viewName);
        final Class<?> viewBeanType = viewBeanExists? beanFactory.getType(viewName) : null;

        if (viewBeanExists && viewBeanType != null && AbstractThymeleafView.class.isAssignableFrom(viewBeanType)) {

            view = (AbstractThymeleafView) beanFactory.configureBean(view, viewName);

        } else if (viewBeanExists && viewBeanType == null) {
...
        } else {
...
        }

        // This is ALWAYS null.
        if (view.getTemplateName() == null) {
            view.setTemplateName(viewName);
        }
```

**Comment by danielfernandez** [comment]
The problem is the `ThymeleafViewResolver` does not look for existing beans with the required name in order to directly use them, but instead only to use them as _prototypes_. That is why the `View` object is always instantiated using `BeanUtils.instantiateClass(...)` even if after that the resolver tries to configure it using an existing _bean definition_ at the `beanFactory.configureBean(...)` call.

In your case, it is your specific bean instance the only one that knows the `/protocol/responseView` template name because you've passed it in the constructor of the object. Using Spring's XML configuration and the `setTemplateName` setter instead of the `ThymeleafView(templateName)` constructor, Spring would consider your bean a _bean definition_ and be able to apply the template name in that `configureBean(...)` call. But I'm not sure how this can be achieved using Spring's Java configuration and I don't think `@Scope("prototype")` would help… perhaps a limitation?

As for the reasons why the `ThymeleafViewResolver` doesn't directly pick that bean and instead creates a new object, the reason is the mutability of the `View` instances, which would be a problem if the same bean was shared across multiple threads. Once instantiated and configured, a `View` object still has to be set a `locale`, a `characterEncoding`, some variables that depend on the specific `ViewResolver` that resolved it (there might be several), and even the specific `TemplateEngine` instance that will be used for processing the template for that `View`.

Note also that this _mutability_ of views is not a Thymeleaf-specific behaviour. It's what Spring does for other `ViewResolver` implementations like e.g. `InternalViewResolver` (the one for JSPs).

However, note that **you don't have to use `ThymeleafViewResolver` for this**. You could also completely build your `ThymeleafView` object, set all its fields (including the `templateEngine`), do all other initialisations performed at the `ThymeleafViewResolver` and make sure that you never need to modify anything on that bean (because of mutability + view object being shared). And then just use a Spring `BeanNameViewResolver` for it. And in that case you'd be sure that Spring would be returning exactly your bean instance.
