### ISSUE TITLE
Add th:object to TEXT template mode

### ISSUE THREAD

**Issue by sluramod** [thymeleaf/thymeleaf-spring#105]
SpringObjectTagProcessor works only in HTML mode. org.thymeleaf.spring4.expression.Fields does not work in TEXT mode because it is not possible to bind object using th:object. 

It's very small change, but very useful IMO.

**Comment by danielfernandez** [comment]
This is made on purpose. There is `th:object` in `TEXT` template mode, but as you say it is the version of `th:object` that simply selects an object and allows `*{...}` expressions to be executed, it does not enable Spring form binding.

The reason for this is that `th:field` make no sense in `TEXT` mode. `th:field` is an HTML-oriented attribute that acts on the `value`, `name` and `id` fields of an `<input>`, `<select>` or `<textarea>` tag, but in `TEXT` mode there are no such things as those tags... simply text. 

If an element such as `[# th:field="*{name}"/]` was written, it would have no effect because it would be turned into something like `[# id="name" name="name" value="somevalue"/]` and then simply disappear, because `[# .../]` elements do not appear in output.

As for the `#fields` expression object you mention, there is no need for it to live inside a `th:object`, so this shouldn't be an issue in `TEXT` mode. You should be able to call it using the name of your form bean in a `${...}` expression, like `${#fields.hasErrors('${myBean.myField}'}`.

**Comment by sluramod** [comment]
> This is made on purpose.

So maybe you can reconsider, since there are no side effects. Here is my scenario: I found that it's easier for me to use text mode to handle html templates. I use the following template:

`[# th:object="${formObject}"]`
`<form>...`
`<input name="email" value="[[*{email}]]"/></td>`
`[# th:insert="classpath:/views/common/field_error (name='email')" /]`
`</form>`
`[/]`

You are right that I can use `#fields` with bean name prefixed, but it does not look good when value is not prefixed, but `#fields` is.
