### ISSUE TITLE
Thymeleaf would not resolve quotes or &rsquo; from a spring model attribute

### ISSUE THREAD

**Issue by steelow** [thymeleaf/thymeleaf-spring#114]
How do I get thymeleaf to resolve my model attribute? 

I would like to make the default input value out of `${title} = "Wayne&rsquo;s World"` model property coming from the controller, 

I have the following: 

`<th:block th:include="row::row(attrs='value=\'__${title}__\', minLength=\'.{1, 16}\', required=true, title=\'starts with an alphabet 1 and 64\', placeholder=\'Movie title\'')" />`

It just simply produce an input element with `"Wayne&rsquo;s World"` instead of `"Wayne's world"`. 

However, using `${title} = "Wayne's World"` or `"Wayne\'s World"` throws parsing error in the thymleaf template engine. 

Any way to resolve this? 

Thank you in advance

**Comment by danielfernandez** [comment]
How is that `attrs` fragment attribute being used inside the `row :: row` fragment? Depending on that (e.g. whether you are using `th:text`, `th:utext`, and inlined expression…) Thymeleaf will apply HTML escaping or not to your large text literal value.

I'm not sure anyway if what you are expecting and/or obtaining at the HTML level (not the browser display level) is `Wayne&rsquo;s World` (which would display at the browser as `Wayne’s World`) or `Wayne&amp;rsquo;s World` (which would display at the browser as `Wayne&rsquo;s World`). 

Also, I'm not sure either of the real content of the `title` variable in your context…

Could you please clarify these points?

As for directly using quotes, it will depend again on your use of the `attrs` argument.

**Comment by steelow** [comment]
Here is the `${attrs}` usage in my `row::row` fragment
`<input th:if="${attrs}" th:attr="__${attrs}__" />`

By the way, `${title}` goes into the html input value attribute.

**Comment by danielfernandez** [comment]
Could you please clarify:
- What exactly you are obtaining in your HTML (not what your browser displays, but what you obtain at your HTML code).
- What exactly you were expecting instead.
- What is exactly the value of the `title` context variable.

**Comment by steelow** [comment]
The html contains `&rsquo;`
I expect an apostrophe to be displayed whether the html using the `&rsquo;` code or `'`.
When `${title}` contains either `Wayne's World` or `Wayne\'s World`, Thymeleaf throws a parsing exception.
When `${title}` contains `Wayne&rsquo;s World`, Thymeleaf outputs it as is.

**Comment by steelow** [comment]
I suppose that this may not be possible with thymeleaf. Most likely a bug. Any decent template should be able to reproduce a valid model attribute without throwing parsing exceptions even if  that attribute contains an apostrophe or whatever else. Thymeleaf claims to be able to do this but throws parsing exception for `${title} = Wayne's World`. Sad indeed!

**Comment by danielfernandez** [comment]
:smile:

> When ${title} contains either `Wayne's World` or `Wayne\'s World`, Thymeleaf throws a parsing exception.

Because in the first case this is **invalid** syntax:

``` html
<!-- single quote in "Wayne's" breaks the literal set as a value of "attrs" -->
<th:block th:include="row::row(attrs='value=\'Wayne's World\', minLength=...')" />
```

And in the second case this is _valid_ syntax:

``` html
<th:block th:include="row::row(attrs='value=\'Wayne\'s World\', minLength=...')" />
```

...but then it results in this, which is **invalid** syntax too:

``` html
<!-- single quote in "Wayne's" breaks the literal set as a value of "value" -->
<input th:if="${attrs}" th:attr="value='Wayne's World', minLength=..." />
```

> When `${title}` contains `Wayne&rsquo;s World`, Thymeleaf outputs it as is.

So it works as expected.

**Comment by steelow** [comment]
I think you have misunderstood. Here is the situation:

`${title} = "Wayne's World"`

`<th:block th:include="row::row(attrs='value=\'__${title}__\', minLength=\'.{1, 16}\', required=true, title=\'starts with an alphabet 1 and 64\', placeholder=\'Movie title\'')" />`

`row::row` fragment is as follows:

`<th:block th:fragment="row">
    <input th:if="${attrs}" th:attr="__${attrs}__" />
</th:block>`

Hope this helps.

By the way, thank you for assisting me in looking into this. I appreciate.

**Comment by danielfernandez** [comment]
Again:

```
${title} = "Wayne's World"
```

So:

``` html
<th:block th:include="row::row(attrs='value=\'Wayne's World\', minLength=...')" />
```

Which is a syntax error. You are closing the literal after "Wayne".

**Comment by steelow** [comment]
What is the meaning of your response?

**Comment by danielfernandez** [comment]
Here:

``` html
<th:block th:include="row::row(attrs='value=\'__${title}__\', minLength=...')" />
```

You are applying _expression pre-processing_ with `__${title}__`. That means that **before** the value of `th:include` is evaluated as a Standard Thymeleaf expression, the `${title}` expression will be evaluated as an expression apart and its result will be literally used for replacing `__${title}__`.

So if  `${title}` has the value `Wayne's World`, your `<th:block>`'s `th:include`, at the moment it is truly evaluated as a `th:include`, will look like this:

``` html
<th:block th:include="row::row(attrs='value=\'Wayne's World\', minLength=...')" />
```

So parsing of the `th:include` attribute value will start, and everything between those `(...)` parentheses will be parsed as _fragment parameters_. I'm here abbreviating everything from `minLength=` because it is obviously not relevant.

So the first parameter to be evaluated as such will be `attrs`, which value should be… _oops!_ problem.

Why problem? because the value of `attrs` will be considered the literal that comes after the `=` sign, and that is `value=\'Wayne`, as you can see (starts with a non-escaped single quote, ends with another non-escaped single quote). So the parser will see that after this literal there is a string such as `s World\', minLength=...'` that is not a _second fragment parameter_, because if it were so it would be prefixed with a separating comma, which it isn't, and it would have the `name=value` shape, which it hasn't.

So that is a syntax error.

**Comment by steelow** [comment]
I knew that the engine was doing this. Which is why I was asking if there is a way to still display the `${title}` containing `'`. The reason this case is so crucial is that `${title}` is indeed a user input which was supposed to be re-rendered from the model back to the user as a default input value. Should users be instructed not to input certain characters because thymeleaf engine would not be able to render them?

**Comment by danielfernandez** [comment]
> I knew that the engine was doing this

Sorry, I might have misunderstood your _"Any decent template should be able to reproduce a valid model attribute without throwing parsing exceptions even if that attribute contains an apostrophe or whatever else. Thymeleaf claims to be able to do this but throws parsing exception for `${title} = Wayne's World`. Sad indeed!"_

It didn't look to me as if you were understanding that your code was actually causing those parsing errors.

> Should users be instructed not to input certain characters because thymeleaf engine would not be able to render them?

Well, IMHO no. In fact most Thymeleaf applications obviously do this all the time. I'd just not use pre-processing so much to embed your values into literals (which forces you to add a level of literal-escaping, which is giving you trouble), and simplify your code to end up doing something more _standard_ like:

``` html
<input th:value="${title}" />
```

Or even, if you prefer it to be more generic, something like:

``` html
<input th:value="${value}" />
```

...having first called your `row::row` fragment with:

``` html
<th:block th:include="row::row(value=${title}, ...)" />
```

In the code above, note how a `value` fragment parameter is directly set to `${title}` (simply a context variable) and not to `'__${title}__'` (a literal into which preprocessing will write `${title}`'s value, potentially causing issues with literal-escaping like the ones you had).

So, I would recommend:
- Not to use that single `attrs` parameter with such a large literal value. Needing to transform everything to a Thymeleaf expression literal is the key to your issues here, I think, due to the need these literals have of escaping single quotes. I'd use several parameters instead, each with its own value, which might be a Thymeleaf literal or anything else (e.g. `${title}`, which is the value of the `title` context variable, whatever that value is, and whatever its type).
- Also (though this is optional), not to use that `th:attr` for setting all the attributes in your input. You can use `th:value`, `th:placeholder`, `th:title`, `th:required`... there is no `th:minLength` because that is not a standard HTML attribute, but you can use `th:attr` specifically for that one and yet your code will be cleaner IMHO. However, note that the use of `th:attr` is not causing you any issues here, but rather its use with a single _pre-processing-based_ value such as `th:attr="__${attrs}__"`. If you still prefer to use `th:attr`, I would go for something like `th:attr="value=${value}, minLength=${minLength}, placeholder=${placeholder}, ..."` though I'd definitely prefer `th:attr="minLength=${minLength}" th:value="${value}" th:placeholder="${placeholder}" ...`.

This said: I've tried to help you, I believe, quite a lot. I've made an effort and invested a good amount of time in understanding your scenario and try to help you solve your doubts. I hope you understand that your belligerent tone and sarcasms are not helping my will to help. Please stop, or I will simply lock this conversation and leave it here.

**Comment by steelow** [comment]
I did not intend to be belligerent nor sarcastic. My sympathies - if you felt that I were. For over a week, I have tried anything and everything to resolve this issue to no avail in. Folks at stackoverflow could not help either. In my many years in this business, I have never encountered a template engine that could not handle this use-case. I am simply voicing my frustration that this state of the art template engine cannot. That's all. 

I had considered using the `th:value, th:placeholder...` The html attributes that will be supplied to the fragment could only be known at runtime, So this approach may not be feasible.

**Comment by danielfernandez** [comment]
> The html attributes that will be supplied to the fragment could only be known at runtime, So this approach may not be feasible.

There would be ways to use this approach anyway. However, you can still stick to your `th:attr` and `attrs` parameter. Only do not use pre-processing:

``` html
<th:block th:include="row::row(attrs='value=${title}, minLength=...')" />
```

The code above will cause no issues at all with escaping the value of your `title`.

Then you can still use:

``` html
<input th:if="${attrs}" th:attr="__${attrs}__" />
```

...and the equivalent result will be, still without any literal-escaping issues:

``` html
<input th:attr="value=${title}, minLength=..." />
```

That should do.

As a side note: this will work because the `title` context variable is still available in your fragment. Fragment signatures are not exclusive, i.e. you don't only have the variables in your signature available for your fragment, they are just a tool that allows you to add new variables, or rename some, so that you can make your fragment more generic.
