### ISSUE TITLE
configure multiple templateResovler,Is always the first to take effect?

### ISSUE THREAD

**Issue by xiangyang2516** [thymeleaf/thymeleaf-spring#118]
@Bean
    public TemplateEngine templateEngine() {
        SpringTemplateEngine engine = new SpringTemplateEngine();
        engine.addTemplateResolver(this.fileTemplateResolver());
        engine.addTemplateResolver(this.classLoaderTemplateResolve());
        engine.addDialect(new Java8TimeDialect());
        return engine;
    }
  private ITemplateResolver fileTemplateResolver() {
        FileTemplateResolver templateResolver = new FileTemplateResolver();
        templateResolver.setPrefix(this.properties.getPrefix());
        templateResolver.setSuffix(this.properties.getSuffix());
        templateResolver.setTemplateMode(this.properties.getMode());
        templateResolver.setCacheable(this.properties.isCache());
        templateResolver.setCharacterEncoding("UTF-8");
        templateResolver.setOrder(1);
        return templateResolver;
    }

```
private ITemplateResolver classLoaderTemplateResolve() {
    ClassLoaderTemplateResolver templateResolver = new ClassLoaderTemplateResolver();
    templateResolver.setPrefix("templates/");
    templateResolver.setSuffix(".html");
    templateResolver.setTemplateMode("HTML");
    templateResolver.setCacheable(false);
    templateResolver.setCharacterEncoding("UTF-8");
    templateResolver.setOrder(2);
    return templateResolver;
}
```
## The official document says：

> all the view resolvers in the application execute in ordered chain until one of them is able to  resolve that view, in which case a View object is returned and control is passed to it for the  renderization of HTML.

**Comment by xiangyang2516** [comment]
.....

**Comment by danielfernandez** [comment]
Please note there is a `resolvablePatterns` property which is the one to determine (by means of patterns that can have a `*` wildcard) whether a template resolver will consider a view name to be resolved by it or not.

Also, since 3.0 there is a `checkExistence` property which allows the template resolver to actually perform a check on the physical existence of the resource as a way to determine whether it should consider the resolution successful or not.
