### ISSUE TITLE
How to display form errors without using th:object

### ISSUE THREAD

**Issue by nagaifelze** [thymeleaf/thymeleaf-spring#126]
I am getting below error :
```
Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Could not
bind form errors using expression "*". Please check this expression is being 
executed inside the adequate context (e.g. a <form> with a th:object attribute)
(reset_password:70)
```
Why should I always use ModelAtrribute and th:object to display form errors. I want to simply use submit the form and get request parameters and add and display if there are any form errors. I dont want to create any object to hold the form data.

**Comment by danielfernandez** [comment]
The concept of form binding and how it relates to error handing is part of the Spring architecture, not Thymeleaf's. Thymeleaf simply gives you access to all of that.

Spring will create `BindingResult` objects in the model for each object in it involved in form binding, and Thymeleaf will let you access these `BindingResult` objects after submission in order to check if there are any associated errors, the fields they refer to (if any, etc.).

So the part of your comments that refer to how form binding is done should probably be debated in a Spring forum rather than here. As for the use of `th:object`, however, note that Thymeleaf allows you to check the errors associated with any form-bound object from outside the form (and outside the `th:object`, therefore. Check this: http://www.thymeleaf.org/doc/tutorials/3.0/thymeleafspring.html#displaying-errors-outside-forms

I'm therefore closing this ticket for now. If there are further comments or issues you might want to remark, please feel free to reopen it. Thanks.
