### ISSUE TITLE
How can I get ApplicationContext from IExpressionContext?

### ISSUE THREAD

**Issue by kasecato** [thymeleaf/thymeleaf-spring#127]
* version: 
  * thymeleaf-3.0.3.RELEASE
  * thymeleaf-spring4-3.0.3.RELEASE
  * org.springframework:spring-webmvc-4.3.3.RELEASE

I'd like to implement `IExpressionObjectDialect` and get Spring `ApplicationContext` from `IExpressionContext`.

I already tried `org.thymeleaf.spring4.context.SpringContextUtils`, but it failed to cast `ThymeleafEvaluationContextWrapper` to `ThymeleafEvaluationContext` error.

I temporarily solved this issue with the following reflection.

How can I get `ApplicationContext` from `IExpressionContext`?

```java
public class TempSpringContextUtils {

    public static final ApplicationContext convert(IExpressionContext expressionContext) {

        final ITemplateResolver springResolver = expressionContext.getConfiguration().getTemplateResolvers()
                .stream().filter(resolver -> resolver instanceof SpringResourceTemplateResolver).findFirst().orElse(null);
        if (springResolver == null) {
            return null;
        }

        Field applicationContextField;
        try {
            applicationContextField = ((SpringResourceTemplateResolver) springResolver).getClass().getDeclaredField("applicationContext");
        } catch (NoSuchFieldException e) {
            return null;
        }
        applicationContextField.setAccessible(true);

        ApplicationContext applicationContext;
        try {
            applicationContext = (ApplicationContext) applicationContextField.get(springResolver);
        } catch (IllegalAccessException e) {
            return null;
        }

        return applicationContext;
    }

}
```

```java
public class Color extends AbstractDialect implements IExpressionObjectDialect {

    private static final String NAME = "Color";

    protected Color() {
        super(NAME);
    }

    @Override
    public IExpressionObjectFactory getExpressionObjectFactory() {
        return new ThemeExpressionObjectFactory();
    }

    private static class ThemeExpressionObjectFactory implements IExpressionObjectFactory {

        private static final String EXPRESSION = "color";

        private final Map<String, Function<ApplicationContext, ColorModel>> expressionObjects = new HashMap<String, Function<ApplicationContext, ColorModel>>() {
            {
                put(EXPRESSION, applicationContext -> applicationContext.getBean(ColorModel.class));
            }
        };

        @Override
        public Set<String> getAllExpressionObjectNames() {
            return expressionObjects.keySet();
        }

        @Override
        public Object buildObject(final IExpressionContext context, final String expressionObjectName) {
            if (!expressionObjects.containsKey(expressionObjectName)) {
                return null;
            }
            
            final ApplicationContext applicationContext = SpringContextUtils.getApplicationContext((ITemplateContext) context);
            if (applicationContext == null) {
                return null;
            }

            return expressionObjects.get(expressionObjectName).apply(applicationContext).build(context);
        }

        @Override
        public boolean isCacheable(String expressionObjectName) {
            return false;
        }
    }

}
```

**Comment by danielfernandez** [comment]
As you describe, there was an incorrect behaviour at `SpringContextUtils`, which assumed the Thymeleaf Evaluation Context to be of class `ThymeleafEvaluationContext` but didn't take into account the possibility that it could be a wrapper.

The `ThymeleafEvaluationContext` object is created and set into the Thymeleaf context by `ThymeleafView` and `ThymeleafReactiveView` at Spring view rendering time, so every time you execute Thymeleaf as a view for a Spring web app, it will be there and you will be able to use `SpringContextUtils` to access the `ApplicationContext` from your code.

But, if you are executing your template as something other than a Spring View (like e.g. for generating rich HTML emails), which I assume is your case or similar to it, then the `SPELVariableExpressionEvaluator` will determine there is no Thymeleaf Evaluation Context in place (or it is a different Spring `EvaluationContext` implementation) and simply create a wrapper. But these wrappers do not keep a reference to the `ApplicationContext`, nor they can keep it, because at the moment `SPELVariableExpressionEvaluator` is executed there is no possible way to obtain the `ApplicationContext`.

So I've filed #129 which modifies the behaviour of `SpringContextUtils` to avoid the class cast exception and improve its documentation, stating that it can return `null`. There's not much more that can be done.

Generally speaking though, note that Thymeleaf allows accessing beans in the `ApplicationContext` with the standard SpringEL bean notation `@bean`, like in: `${@usersService.findAllUsers()}`. But using `@bean` in SpringEL actually needs to have an evaluation context to which a bean resolver (such as, precisely, the `ApplicationContext`) has been set. So it might not work in your scenario.

So I'd make the recommendation that you manually add a `ThymeleafEvaluationContext` instance to your context as another variable with name `ThymeleafEvaluationContext.THYMELEAF_EVALUATION_CONTEXT_CONTEXT_VARIABLE_NAME`. That should give you the ability to both access the `ApplicationContext` using `SpringContextUtils`, and also access any bean in your template expressions just like `@bean`.
