### ISSUE TITLE
Engine with multiple template resolvers fails to resolve template

### ISSUE THREAD

**Issue by ptahchiev** [thymeleaf/thymeleaf-spring#130]
Hello,

with Thymeleaf2 and Spring4 I was able to have a templateEngine and define several template resolvers to it:
````
        SpringTemplateEngine engine = new SpringTemplateEngine();

        engine.addTemplateResolver(thymeleafSpringResourceTemplateResolver());
        engine.addTemplateResolver(new InMemoryTemplateResolver());

        return engine;
````
and the flow was going like this:
1) it tries to find the template from the TemplateRepository:

https://github.com/thymeleaf/thymeleaf/blob/2.1-old-dev/src/main/java/org/thymeleaf/TemplateEngine.java#L1192

2) inside that `TemplateRepository` it loops over all registered templateResolvers:

https://github.com/thymeleaf/thymeleaf/blob/2.1-old-dev/src/main/java/org/thymeleaf/TemplateRepository.java#L205

until it finds a templateResolver which returns an InputStream != null. So in my case `thymeleafSpringResourceTemplateResolver` would return null but then it would fallback to `InMemoryTemplateResolver` which would find the resource just fine.

Now I'm trying to switch to Thymeleaf3 with Spring5 and I see that inside TemplateEngine we no longer have a TemplateRepository and if I try to specify a template which can only be found by `InMemoryTemplateResolver` I get an exception. And the reason for the exception is that `SpringResourceTemplateResource` has a method called reader() which tries to get the `InputStream` of a resource:

https://github.com/thymeleaf/thymeleaf-spring/blob/3.0-master/thymeleaf-spring5/src/main/java/org/thymeleaf/spring5/templateresource/SpringResourceTemplateResource.java#L103

which throws a `FileNotFoundException` which is never handled and it never goes to try the `InMemoryTemplateResolver`.

I think it's a bug

**Comment by danielfernandez** [comment]
This is expected behaviour in Thymeleaf 3.

In Thymeleaf 2.1, the way template resolvers behaved when they were asked to resolve a resource that didn't exist was not directly predictable and depended on the specific implementation of the resolver. So simply chaining resolvers without using the `resolvablePatterns` property in these resolvers to determine which templates could be resolved by each step in the chain could work or not, depending on the specific combination of these resolvers that was being used.

As of Thymeleaf 3.0, this was normalized into a behaviour that mirrors (to the extent possible) the resource resolution mechanism in Spring. Also, a general refactoring of the resolution mechanism allowed avoiding double-access to template resources in order to determine their existence –which could be costly if the resource is remote– if this was not necessary. 

So in 3.0, when template resolvers in a chain are expected to be able to pass resolution to the next element in the chain, they should:

   * Either have their `resolvablePatterns` property configured to match the templates it is able to resolve.
   * Or have their `checkExistence` property (new in 3.0) set to `true` so that the real existence of the resource is actually checked before considered it *resolved*. Default is `false`.

In your case, if your template resources are local and you use the template cache, double-access will most probably not be an issue, so setting `checkExistence` to `true` on your first resolver should be enough.
