### ISSUE TITLE
[THYMELEAF][restartedMain] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.

### ISSUE THREAD

**Issue by tianmingxing** [thymeleaf/thymeleaf-spring#137]
When the project configuration is as follows, the above warning is caused:

```
thymeleaf:
   cache: false
   mode: HTML5
```

After the prompt is modified, a warning message is found.

```
thymeleaf:
   cache: false
   mode: HTML
```

Although this problem is solved, but I found some other problems. Do I think the default value of "MODEL" needs to be fixed? 

```
/**
  * Template mode to be applied to templates. See also StandardTemplateModeHandlers.
 */
private String mode = "HTML5";
```

After editing the above, the editor will appear alarm.

![wx20170408-230408](https://cloud.githubusercontent.com/assets/5615719/24830007/b8f7694a-1caf-11e7-85c4-49182b8a087f.png)

**Comment by danielfernandez** [comment]
That warning is expected behaviour. Current stable versions of Spring Boot use Thymeleaf 2.1 by default, which has a template method called `HTML5`, and so it is configured by default at the Spring Boot autoconfiguration artifacts.

But apparently you have updated the version of Thymeleaf to be used by Spring Boot to Thymeleaf 3.0 (which is fine, and supported), and in such case the template mode auto-configured by Spring Boot raises a warning, because `HTML5` does not exist anymore in Thymeleaf v3.0. It was deprecated and replaced by `HTML`. Thymeleaf is handling this automatically for you, but it will issue that warning you are seeing unless you change this in your `application.properties` or `.yml`
