### ISSUE TITLE
Thymeleaf 3.0 - writing template to response stream causes choppy rendering

### ISSUE THREAD

**Issue by nkramaric** [thymeleaf/thymeleaf-spring#148]
I am noticing in my server-side rendering heavy Java Spring application, Thymeleaf 3.0 renders more choppy than 2.0. This was something that was raised in the Thymeleaf forum as well: http://forum.thymeleaf.org/Thymeleaf-3-upgrade-rendering-td4030379.html 

I have narrowed down the issue to the fact that Thymeleaf 3.0 writes the template as its generated to the response stream. I have updated the code to write to the stream once the entire template is in memory: https://github.com/nkramaric/thymeleaf-spring/commit/cac98400ed0ea4c4e7c19a6ac9a12e2450c8aace

With this update, in my use case, the page renders much more smoothly. I realize this may not be the case for everyone, but for me in-particular, the entire page will reload on many user actions and even the slight increase it the streamed rendering instead of the instantaneous one in my proposed solution is a big deal. Is this something that can be added as a configurable option?

**Comment by danielfernandez** [comment]
To be honest, I'm struggling to see how this should be seen as an advantage, and not an issue at the browser side / client code.

Even if Thymeleaf sent all the HTML only once it is ready –and assuming we can forget about the potentially large amounts of server memory this could waste–, there is nothing in this proposed method that would guarantee an *instantaneous* transfer of the HTML to the browser.

Say, if the resulting HTML is 10KBytes in size, and being the typical Tomcat output buffer size 8KBytes, there would still be a piece of HTML being sent, then a wait until the required network roundtrips are completed, and then a second iteration of HTML transmission for the remaining 2KBytes. And this is of course considering access from local, because once network latencies for remote access are in place, there is no way IMHO in which we could predict such *instantaneous* receiving of the HTML by the browser…

So please, could you give more detail on how this is affecting you negatively? I believe Thymeleaf (up to 2.1) was very probably the only Java template engine out there waiting for the entire rendering to complete before sending the results, so this kind of request to allow it to be *worse performing* is to be honest a bit surprising to me…

@ultraq you are the client-side expert here… any comments on this that might help?

**Comment by ultraq** [comment]
I don't really have much more to add than what I put in the linked forum thread where I explained why, with Thymeleaf 3, the UI appears to jump with very large HTML pages.

But I am very on the fence about this feature request.  Here's my thinking:

My initial reaction is to direct those those affected by this issue (mostly devs who have worked on Thymeleaf 2.1 web apps that are sending a crazy amount of HTML down the wire and making the upgrade to Thymeleaf 3) to take this as an opportunity to learn more about the browser environment (there is some false belief that the browser is capable of the infinite amounts of HTML/CSS/JavaScript we throw at it, but as we've seen it's far more resource constrained and slower than you'd think the moment you step away from dev'ing on your local machine).  Then, armed with this knowledge, craft user experiences that work much better within these constraints: rendering less HTML, re-rendering *only* the parts that change in an on-demand fashion, backing-off from JS code that tries to do or inspect layout and letting the browser do its job, etc.

That paragraph above is my ideal.  However, not all devs live in the world where they have the time to be able to do that.  Also, the language about the 2.1 -> 3 upgrade was very much about being a drop-in replacement for 2.1 code - we don't say anything like "now that the server is streaming the HTML your UI might need some rework".

Then again, this was a major version upgrade, and in semantic versioning parlance major version upgrades should come with the proportional amount of developer due-diligence in evaluating the upgrade.

So as you can see, I'm a bit torn on what to do 😕

**Comment by danielfernandez** [comment]
Note that via #113 a new `producePartialOutputWhileProcessing` has been developed that allows app developers to go back to the old process-then-render behaviour in 2.x. Not _exactly_ the same though, because Thymeleaf 2.x resolved the DOM tree before rendering and sending to the output buffers, and Thymeleaf 3.0 will (if configured) actually render the entire HTML into memory (no DOM in v3!) before sending to the output buffers.

Please note that this setting can have a very significative (bad) effect in memory consumption at the server.
