### ISSUE TITLE
BindingResult never makes it into the template so that errors cannot be displayed

### ISSUE THREAD

**Issue by odrotbohm** [thymeleaf/thymeleaf-spring#169]
I have a Spring Data form binding interface like this:

```java
interface GuestbookForm {

	/**
	 * Returns the value bound to the {@code name} attribute of the request.
	 * 
	 * @return
	 */
	@NotBlank
	String getName();

	/**
	 * Returns the value bound to the {@code text} attribute of the request.
	 * 
	 * @return
	 */
	@NotBlank
	String getText();

	…
}
```

and a Spring MVC controller method using that interface to bind the form as well as an `Errors` instance to collect binding errors:

```java
@PostMapping(path = "/guestbook")
String addEntry(@Valid GuestbookForm form, Errors errors, Model model) {

	if (errors.hasErrors()) {
		return guestBook(model, form);
	}

	guestbook.save(form.toNewEntry());
	return "redirect:/guestbook";
}
```

While the `Errors` object that gets handed into the controller carries the errors, in the form below, they're inaccessible, i.e. `#fields.hasErrors('*')` returns false, error CSS classes are not set etc:

```html
<form method="post" role="form" class="gb-form" id="form" th:action="@{/guestbook}" th:object="${form}">
		
	<div th:if="${#fields.hasErrors('*')}">Entry has errors!</div>
		
	<div class="form-group">
		<label for="name" th:text="#{guestbook.form.name}">Name</label><br /> 
		<input class="form-control" type="text" th:field="*{name}" th:errorclass="fieldError" /><br /> 
	</div>

	<div class="form-group">
		<label for="text" th:text="#{guestbook.form.text}">Text</label><br /> 
		<textarea th:field="*{text}" th:errorclass="fieldError" class="form-control"></textarea><br /> 
	</div>

	<input type="submit" class="btn btn-default" th:value="#{guestbook.form.submit}" value="Senden" />

</form>
```

Here's what I've noticed and debugged already:

- The controller method argument *not* carrying an `@ModelAttribute` is not an oversight. It needs to be that way so that the standard Spring form binding doesn't get active but Spring Data's special interface binding.
- I've debugged into `FieldUtils.getBindStatusFromParsedExpression(…)` and can see that the `requestContext` that's obtained in the first step doesn *not* contain the `Errors` instance that the controller sees but an empty one.
- This leads me to the assumption that Thymeleaf sort of loses the connection between the model object `form` and the associated `Errors` instance.
- I failed to find the code that makes Thymeleaf aware of the binding result produced by Spring MVC in the first place.

You can find a reproducing sample project [here](https://github.com/st-tu-dresden/guestbook). Steps to reproduce:

```
$ git clone https://github.com/st-tu-dresden/guestbook
$ cd guestbook
$ git co thymeleaf
$ mvn spring-boot:run
```

Browse to http://localhost:8080, submit the empty form. See the page redisplayed without any errors. Put a breakpoint in `GuestbookContoller.addEntry(…)` and see the `Errors` instance actually carrying errors.

**Comment by danielfernandez** [comment]
As you noticed, the issue here is because the standard behaviour in Spring MVC is to name the model attribute representing the bound form starting from the name of of the class, not the name of the argument in the controller method, so if you had something like:

```java
@PostMapping(path = "/guestbook")
String addEntry(@Valid GuestbookForm form, Errors errors, Model model) {

	// Let's see what Spring MVC has put inside the Model already
	System.out.println(model.asMap());

	if (errors.hasErrors()) {
		return guestBook(model, form);
	}

	guestbook.save(form.toNewEntry());
	return "redirect:/guestbook";
}
```
...at that `model.asMap()` there you would be able to see two attributes already:

   * `guestbookForm` of type `GuestbookForm`
   * `org.springframework.validation.BindingResult.guestbookForm` of type `org.springframework.validation.BeanPropertyBindingResult`

So the `BindingResult` object is indeed there, but will not be recognized at the template when showing the errors because the name that has been given to the form-binding variable is just `form` (and not `guestbookForm`):

```html
<form ... th:object="${form}">
```

The thing is, the `#fields.hasErrors('*')` expression will look for errors (actually for a `BindingResult` object) by appending that `*` meaning *all fields* to all the information about the form that it has got in that moment of template execution, and that information is simply the name of the form-backing bean model attribute. But that form-backing bean model attribute has been specified in the `<form th:object="...">` as `form`, not `guestbookForm`, so it will look for a `Bindingresult` object in `org.springframework.validation.BindingResult.form`, which does not exist. Hence no errors are shown.

So there is a mismatch between the chosen naming and the default Spring behaviour for naming form objects as model attributes. The name in `th:object` and the name given to the form as a model attribute must match for this mechanism to work. And by the way I don't believe this is correctly explained in the Thymeleaf docs so that's something to be improved...

The first way to fix this in other type of Spring MVC app would be by means of adding that `@ModelAttribute("form")` to the request parameter... but indeed as you say, you cannot use that in this case.

So I think the only thing left would be to rename the form-binding model attribute to `guestbookForm` to match the standard behaviour.

I'd personally do two modifications for this: first let this standard behaviour act on the `guestBook` method itself by not explicitly adding the form to the `Model`:

```java
@GetMapping(path = "/guestbook")
String guestBook(Model model, GuestbookForm form) {
	model.addAttribute("entries", guestbook.findAll());
	return "guestbook";
}
```
...and second modify the `th:object` in the `<form>` accordingly:
```html
<form ... th:object="${guestbookForm}">
```

**Comment by odrotbohm** [comment]
Indeed, this doesn't seem to be a Thymeleaf issue at all. After discussion with the Spring MVC team I got to tweak Spring Data's projection binding to allow the usage of `@ModelAttribute` against [this ticket](https://jira.spring.io/browse/DATACMNS-1237) fixed with [this commit](https://github.com/spring-projects/spring-data-commons/commit/96d85677030688d61a1a3056fede8a58341754d1).

Feel free to close this one as everything on the Thymeleaf side seems to work as designed.

**Comment by davidnewcomb** [comment]
I just wanted to say thanks very much @danielfernandez for writing a fuller explanation with a bit of background. I have spent most of the day trying to figure out why my objects were all empty. And yes the documentation on this is.... well I ended up here!

I think if you just cut and pasted your answer into section 8.6 of https://www.thymeleaf.org/doc/tutorials/2.1/thymeleafspring.html then it would have saved me a whole day.
