### ISSUE TITLE
Formatting of numbers with th:field 

### ISSUE THREAD

**Issue by McNetic** [thymeleaf/thymeleaf-spring#171]
This is something between an enhancement proposal and a bug report:

Currently, th:field will not apply formatting to input type "number". This obviously results in the default toString() method being used, which uses an exponential notatation for slighlty bigger numbers (for example, 999999999.0 will be formatted as 9.99999999E8). While this is technically not wrong, as html number inputs allow for javascript numeric entries, which also allow the exponential notation, it will in most cases not be what the developer intended.

I'm not exactly sure if or how this could be fixed or enhanced. Maybe it is possible to try and use a non-exponential representation as long as a certain length of the result is not exceeded, or provide some mechanism for the developer to change the current behaviour.

**Comment by danielfernandez** [comment]
The reason `<input type="number">` (and also `range`) are not applied formatting is in order to make the values being output (in the `value` attribute of the tag) compatible with the rendering expected by browsers for those types of input (some browsers display a selector with arrows for this type of input).

The fact is, browsers should correctly understand values such as `value="9.99999999E8"` (for example, my Firefox displays that as `999999999` without issues)...

So I'm not really sure about why this should be an issue... could you please elaborate?

**Comment by danielfernandez** [comment]
Closing as _declined_ for the moment. Please reopen in case there are any new details you would want to provide.
