### ISSUE TITLE
HTML array of names

### ISSUE THREAD

**Issue by dzafe1** [thymeleaf/thymeleaf-spring#173]
How to actually accomplish this in Thymeleaf
 `<input type='text' name='foo[]' />`
I am asking this because I want to add Spring Validation on particular field.

**Comment by danielfernandez** [comment]
Is `foo` an attribute in your form backing bean, of type array (e.g. `String[]`)?

If so, you can simply use `th:field` on that field (like `th:field="*{foo}"`) inside a form with a `<form th:object="${myform}" ...>`. However, note that if that property is an array, and thus multivalued, the adequate type of input would be a `<select ... multiple>` instead of an `<input type="text">`.

If on the contrary you want to use an `<input type="text" th:field="*{foo}" ...>`, write your values as a comma-separated list and have someone automatically convert that listo into a `String[]`, you will need to establish a Spring `Formatter` on that field that performs the conversion to and from the comma-separated list text and the `String[]` in your form. This would be a Spring MVC thing, so I recommend you to have a look at the Spring documentation for formatters to know how to to this.

For more information on `th:field`, please have a look at the *"Spring + Thymeleaf Tutorial"* and its companion *STSM* sample application here: https://www.thymeleaf.org/documentation.html
