### ISSUE TITLE
FieldUtils bean path validation is too restricted

### ISSUE THREAD

**Issue by arne-vandamme** [thymeleaf/thymeleaf-spring#176]
The `FieldUtils#validateBeanPath(CharSequence)` method is too restricted.
It will not accept `propertyMap[my.entryKey]` as a valid bean path, even though it is perfectly valid for Spring.

Workaround is to do a `getBindStatus()` with `optional=false` as that skips the validation and the resulting exception can be caught in outer code.

Sidenote: looks also like `validateBeanPath()` never validates the last character either, the call from `isBound()` strips it (accidentally I assume).

I'll add a small PR with a fix for spring4. 
I did not want to change too much of the existing code without understanding it property, so I just made a quick fix that relaxes the validation when detecting it is inside a key segment. A key can be pretty much any character anyway.

The validation would fail if the key value were to contain either `[`or `]` (escaped). But it looks like the actual`PropertyAccessorUtils#canonicalPropertyName(String)` does not support this case anyway... so I expect this to be reasonably ok.

**Comment by danielfernandez** [comment]
Thanks. I have one question regarding this: could you detail a bit more the scenario in which you end up calling `getBindStatus()` with `optional=true` that provokes this issue? Is this due to the evaluation of a `{{...}}` converted expression from the `SpelVariableEvaluator`?

The tests for this type of binding are in `thymeleaf-tests`, in `/src/test/resources/templateengine/springintegration/[forms|errors]`, by the way (you comment on your PR that you cannot find them). Anyway, I'm trying to add some myself for this case but it would help to know the specific circumstances in which you get this method called that way...

**Comment by arne-vandamme** [comment]
No actually I ran into this issue when creating a custom processor for generating a form-bound control. You can specify a bound property but we specifically do not want to fail if the property is not bound, that's why we used `optional=true`. So it was when I manually call `FieldUtils.getBindStatus()` in my processor.

**Comment by danielfernandez** [comment]
Already in `3.0.10-SNAPSHOT`
