### ISSUE TITLE
Resolver not finding messages in nested template directories.

### ISSUE THREAD

**Issue by virmundi** [thymeleaf/thymeleaf-spring#181]
Version: 3.0.9-Release
Environment: Spring Boot
Extension: thymeleaf-layout-dialect:2.3.0

I wish to use nested fragments. Under templates, I have fragments/header.html. Inside header.html I have 
```html
<!DOCTYPE html>
<html xmlns:th="http://ww.thymeleaf.org">
<body>
  <div data-th-fragment="header">
    <div id="master-links">
      <a href="/#"><span th:text="#{fragments.header.recipes}"></span></a> <a href="/#">Knowledge</a>
    </div>
    <div id="auth-links">
      <a href="/login">Login</a>
      <a href="#">Sign Up</a>
    </div>
  </div>
</body>
</html>
```
Parallel to header.html, I have header_en.properties. I've tried fragments.header.recipes, header.recipes. I can't get the resolver to follow the path.

**Comment by danielfernandez** [comment]
I understand you are using Spring Boot. If using Spring Boot, the standard Spring mechanism for message resolution is applied instead of Thymeleaf's default one. Spring's mechanism is based on `MessageSource` objects pre-declared by Boot's autoconfiguration. By default, this will look for all messages in a `Messages.properties` bundle in `/src/main/resources`.

**Comment by danielfernandez** [comment]
Closing this as no more data has been provided.
