### ISSUE TITLE
Why is the addition of custom message resolvers restricted? (when using SpringTemplateEngine)

### ISSUE THREAD

**Issue by kirmerzlikin** [thymeleaf/thymeleaf-spring#183]
Hi,

My version of *thymeleaf* and *thymeleaf-spring4* is *3.0.9.RELEASE*.

I had a need to extend default `SpringTemplateEngine` by adding custom `IMessageResolver` that would retrieve messages from database. During experimenting and investigation I found out that `SpringTemplateEngine` in its `initializeSpecific` method clears all specified message resolvers and replaces them with either `StandardMessageResolver` or `SpringMessageResolver`. Also this method was made final so I can not override it. 

So to me it looks like I can not reuse `SpringTemplateEngine` and `SpringMessageResolver` functionality and define my custom message resolver in the same time.
Can you please confirm or deny this? And if it is true, can you please explain why is adding custom message resolvers restricted? (I wasn't able to find explanation neither in comments nor in the commit message)

Thanks.

**Comment by danielfernandez** [comment]
The idea is that `SpringTemplateEngine` integrates to the most possible degree with Spring mechanisms. And Spring has its own mechanism for the resolution of messages, the `MessageSource` interface. So it made no sense to keep Thymeleaf's own at the same time.

The normal way to extend message resolution in a Spring-enabled Thymeleaf application is therefore to implement a new `MessageSource` and declare it the way Spring dictates, not a Thymeleaf `IMessageResolver`.

Anyway, if using a different `IMessageResolver` is still a need, instead of using `SpringTemplateEngine` one can directly use `TemplateEngine` (which is the superclass of the former), implement the `ISpringTemplateEngine` interface, add the `SpringStandardDialect` manually and perform any modifications to the default configurations that might be needed.

**Comment by kirmerzlikin** [comment]
@danielfernandez thanks for explanation
