### ISSUE TITLE
AddFormatters method is invalid 

### ISSUE THREAD

**Issue by mpv945** [thymeleaf/thymeleaf-spring#185]
public class ThymeleafConfig extends WebMvcConfigurationSupport { 

    @Override
    public void addFormatters(final FormatterRegistry registry) {
        //registry.addFormatter(varietyFormatter());

        registry.addFormatter(dateFormatter());
        registry.addConverter(new CustomDateConverter());
        super.addFormatters(registry);

    }

dependency (spring-webmvc 5.0.4.RELEASE)
Why custom processing is not triggered ?

**Comment by danielfernandez** [comment]
This is a Spring MVC (or Spring Boot if you use it) configuration issue, not really a Thymeleaf one.

If you use Spring MVC directly (no Boot), instead of `WebMvcConfigurationSupport` you should probably be extending `WebMvcConfigurerAdapter` in a `@Configuration` class also with the `@EnableWebMvc` annotation.

If you are using Spring Boot, simply registering your formatters as beans in the context will do (with `@Bean` or in a `@Configuration` class.
