### ISSUE TITLE
org.springframework.expression.spel.SpelEvaluationException: EL1007E: Property or field 'username' cannot be found on null

### ISSUE THREAD

**Issue by zhubenle** [thymeleaf/thymeleaf-spring#186]
`<form th:object="${user}" method="post">
            <input type="email"  th:name="user.username" th:value="*{username}" />
            <input type="password" th:name="user.password" th:value="*{password}">
    </form>
`

Hi, I have a problem. when user is null, *{username} will Cause the above problem.How can this error be suppressed?

thank you

**Comment by danielfernandez** [comment]
When `user` is null, you cannot avoid that exception because `*{username}` is trying to call `getUsername()` on that object.

If you need to make this expressio null-safe, and assuming you are using Spring (and therefore your expression language is SpringEL), you can do something like `th:value="${user?.username}"`, which is the null-safe version of the expression above in SpringEL

**Comment by xwbGithub** [comment]
为何我试了还是不行啊

**Comment by sofency** [comment]
> 为何我试了还是不行啊

老哥 你解决了吗 我也遇到这样的问题，昨天晚上还能运行，早上起来打开后就无法运行了
` <img class="media-object img-rounded" th:src="${question.user.avatar_url}" alt="..." width="38" height="38">`
`
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1007E: Property or field 'avatar_url' cannot be found on null
`
我在后台都能打印出user但是就是报错

**Comment by toinouH** [comment]
> When `user` is null, you cannot avoid that exception because `*{username}` is trying to call `getUsername()` on that object.
> 
> If you need to make this expressio null-safe, and assuming you are using Spring (and therefore your expression language is SpringEL), you can do something like `th:value="${user?.username}"`, which is the null-safe version of the expression above in SpringEL

@danielfernandez I wanted to thank you again as the ? saved my life.
Love you :)
