### ISSUE TITLE
使用最新版本的springboot和thymeleaf为何无法解析国际化信息？

### ISSUE THREAD

**Issue by singkingcho** [thymeleaf/thymeleaf-spring#187]
展示的内容都是??_zh_CN??，导致真是内容无法展示。

**Comment by singkingcho** [comment]
形如#{login.tips}，无法解析成功。

**Comment by danielfernandez** [comment]
I'm sorry, could you provide an explanation of your issue in English?

**Comment by singkingcho** [comment]
For example, I want to use the following syntax in login.html:

#{msg.tips}. in the same directory with login.html, I added login.properties and login_zh_CN.propeties files and wrote msg.tips=hello  
msg.tips=China   in it.

But the result obtained through #{msg.tips} analysis is  ?? msg.tips_zh_CN??
Why is this?

,

**Comment by danielfernandez** [comment]
I assume (due to the fact that you are filing this in the `thymeleaf-spring` repository) that you are using Spring along with Thymeleaf. In such case, externalized messages would not be searched in `login.properties` for a `login.html` file, but instead Spring's own integrated `MessageSource`-based mechanism would be used. You'd normally have at least one `MessageSource` implementation declared (or auto-configured if you are using Spring Boot) and this would work as the source of your messages.
