### ISSUE TITLE
Should Thymeleaf use the ConversionService of Spring for any attribute processors?

### ISSUE THREAD

**Issue by Antibrumm** [thymeleaf/thymeleaf-spring#19]
I am wondering if the Thymeleaf Spring extension should change the behaviour of for example th:text or th:value to rely on the ConversionService instead of simply calling a toString on the Object. 

I believe that this would solve some inconsistencybetween rendering as an input field where the binding is taking care of this itself and rendering as a th:text or th:value attribute where the formatting needs to be done as an expression.

One example would be Dates/Calendars with JodaTime annotations where the annotation already defines the string format and the xxxToString converters are present in the conversationService but Thymeleaf is not leveraging on this if you echo a date as text.

**Comment by danielfernandez** [comment]
The `th:field` attribute should be taking care of form binding and attribute conversion using the Spring mechanisms. Its aim is precisely this... isn't this working for you?

**Comment by Antibrumm** [comment]
Nono. The th:field is working perfectly. It is using the conversion service as you mention it. 

The improvement i think would be worth taking a look at involves the attribute processors of the main thymeleaf project. Like text and value processors. They are not relying on the ConversionService but on the thymeleaf interal resolution which does somewhere a toString. This is logically because these processors do not rely on spring. 

A short example with a date attribute:
- using th:field this is rendered using the conversionservice of spring. 
- using th:text we need to use th:text="*{dates.format(datefield, format)}" to get the same result. 

It would be a nice improvement if this is not neccessary at that level.
So we could simply write th:text=*{datefield}".

**Comment by mike2002** [comment]
I want to second this feature request. I ran into this issue while converting some jsps to thymeleaf.

**Comment by cachescrubber** [comment]
+1

I also want to second this request. I ran into the issue when creating links using "@{}".

Here is my use case:

Controller: expects a Parameter, "sort" formatted like this: "property,ASC|DESC".

```
public String listEmployees(Model model, Pageable pageable) {
    model.addAttribute("page", employeeService.findAllEmployees(pageable));
    return "employee/list";
}
```

The template like it should be, IMO:

```
<a th:if="${page.hasPreviousPage()}" th:href="@{/employee/list(sort=${page.sort},page=${page.number - 1})}" href="#">&larr; Previous</a>
```

Thymeleaf calls toString() on the page.sort object, which gives "id: ASC". This breaks the Controller, which expects "id,ASC".

I implemented a custom Formatter ("sortFormatter"), which I registered with the Spring MVC context in order to avoid the following:

```
<a th:if="${page.hasPreviousPage()}" th:href="@{/employee/list(sort=${(page.sort != null) ?  beans.sortFormatter.print(page.sort) : 'id'},page=${page.number - 1})}" href="#">&larr; Previous</a>
```

Thymeleaf does not use the registered formatter, so I have to call 'beans.sortFormatter.print(page.sort)' over and over again.

**Comment by cachescrubber** [comment]
I banged my head on this the whole day yesterday and I think I came up with a good solution, at least as a workaround.

The basic idea is to put a formatting helper object into each and every Model using @ControllerAdvice and @ModelAttribute:

```
@ControllerAdvice
public class BaseController {
   @Autowired
   private TemplateFormattingHelper formattingHelper;
   @ModelAttribute("formatter")
   public TemplateFormattingHelper formattingHelper() {
       return formattingHelper;
   }
}
```

The TemplateFormattingHelper provides (web template tailored) access to the underlying Spring ConversionService. The interface is simple, because we are only interested in Object To String conversion:

```
public interface TemplateFormattingHelper {
  String print(Object source);
  String print(Object source, String defaultValue);
}
```

Every time you wish to format an Object using the spring ConversionService, simply call one of the print methods in your view:

```
<a th:if="${page.hasNextPage()}" th:href="@{/employee/list(sort=${formatter.print(page.sort, 'id')},page=${page.number + 1})}" href="#">Next&rarr;</a>
....
<td th:text="${formatter.print(employee.dateOfBirth)}">1971-01-01</td>
```

The implementation of TemplateFormattingHelper is simple enough to include it here:

```
public class ConversionServiceTemplateFormattingHelper implements TemplateFormattingHelper {
  private ConversionService conversionService;
  public ConversionServiceTemplateFormattingHelper(ConversionService conversionService) {
    this.conversionService = conversionService;
  }
  @Override
  public String print(Object source, String defaultValue) {
    if (source == null) {
      return defaultValue;
    }
    String result = "";
    try {
      result = conversionService.convert(source, String.class);
    } catch (ConverterNotFoundException ex) {
      result = source.toString();
    }
    return result;
  }
  @Override
  public String print(Object source) {
    return print(source, "");
  }
}
```

Of course you need to wire up the conversionService (beans.xml example)

```
<mvc:annotation-driven conversion-service="conversionService">
<bean id="conversionService" class="org.springframework.format.support.FormattingConversionServiceFactoryBean">
... wire up conversionService ...
</bean>
<bean id="templateFormattingHelper" class="org.cachescrubber.ConversionServiceTemplateFormattingHelper">
    <constructor-arg ref="conversionService"/>
</bean>
```

Should using the [Spring Formatting and Conversion Service](http://docs.spring.io/spring/docs/3.2.x/spring-framework-reference/html/validation.html#core-convert-ConversionService-API) be the default for Object To String conversion in the thymeleaf-spring3 dialect?

Probably yes, since it is essential that formatted String values match the expectations of the data binding framework, especially when creating links with @{}, as in my initial use case. For simple formatting purposes inside, for example th:text, it would also be a sensible default. Should you wish to use one of the standard formatter utilities like #dates.format(), that would stil be possible as it is now.

**Comment by danielfernandez** [comment]
This has just been implemented at 2.1.0-SNAPSHOT, and will be a part of 2.1.0-beta2.

This implementation is based on a new generic (non-Spring-specific) interface called `org.thymeleaf.standard.expression.IStandardConversionService`, in charge of performing the needed conversions.

Implementations of this interface are registered by the Standard Dialects, and the Spring version delegates to the Spring `ConversionService` existing at the Application Context, if it exists.

For example, given this Spring Formatter: https://github.com/thymeleaf/thymeleaf-tests/blob/20131007/src/test-21/java/org/thymeleaf/engine21/conversion/conversion3/CalendarFormatter.java which is registered at the Spring application context like this: https://github.com/thymeleaf/thymeleaf-tests/blob/20131007/src/test-21/resources/engine21/conversion/conversion3/applicationContext.xml

...then the following test would execute alright: https://github.com/thymeleaf/thymeleaf-tests/blob/20131007/src/test-21/resources/engine21/conversion/conversion3/conversion3-01.thtest

**Comment by danielfernandez** [comment]
@opensource21 yes. `th:text` and all other attribute processors that produce output. See the linked test file in my previous comment: https://github.com/thymeleaf/thymeleaf-tests/blob/20131007/src/test-21/resources/engine21/conversion/conversion3/conversion3-01.thtest

**Comment by danielfernandez** [comment]
Important: this feature will be modified by thymeleaf/thymeleaf#222

**Comment by danielfernandez** [comment]
Important: after discussion in thymeleaf/thymeleaf#222, the definitive implementation is explained in thymeleaf/thymeleaf#223
