### ISSUE TITLE
th:field should interpret the string first

### ISSUE THREAD

**Issue by opensource21** [thymeleaf/thymeleaf-spring#20]
If you have a code like this it's inconsistent. The fId it set with th:with and I want to use it.

```
         <div class="control-group" layout:include="templates::bsfield" th:with="fId='tags'" th:remove="tag">
            <label class="control-label" th:remove="all">Last Name</label>
            <div class="controls" th:remove="tag">
                <span layout:fragment="bsinput">
                    <select th:field="*{__${fId}__}" multiple="multiple" th:unless="${disabled}">
                        <option th:each="item : ${tags}" th:value="${item.id}" th:text="${item.name}" th:disabled="${not item.active}"></option>
                    </select>
                    <ul th:if="${disabled}">
                        <li th:each="item : *{${fId}}"  >
                            <a th:href="@{#{url.tag.show(${item.id})}}" th:text="${item.name}">Wichtig</a>
                        </li>
                    </ul>
                </span>
            </div>
        </div>
```

You can wrote `<li th:each="item : *{${fId}}" >` but you must wrote `th:field="*{__${fId}__}"` The nicer code `th:field="*{${fId}}"` doesn't work.

**Comment by danielfernandez** [comment]
That `th:field="*{${fId}}"` is not correct expression syntax in Thymeleaf. The asterisk syntax (`*{...}`) does not mean _field selection_ but just _execute this expression on the object previously selected with `th:object` instead of on the context root_. That's why it is used for field selection in `th:field` attributes.

The content of an `*{...}` is passed to the OGNL/SpringEL expression engine to execute just like `${...}` expressions are (the only change is _on what they are executed_), and of course `${fId}` is not a valid OGNL or SpringEL expression, so it fails.

I'm afraid your options are `*{__${fId}__}` (which you don't seem to like) or `${#object[fId]}` which works in OGNL and I think should also work in SpringEL.

I'm closing this as an issue.

**Comment by opensource21** [comment]
Sorry I can't follow your arguments. My main-point is the inconsistency: For `<li th:each="item : *{${fId}}" >` it works for `th:field` not.  Can you explain the difference?
