### ISSUE TITLE
Cache busting not working

### ISSUE THREAD

**Issue by black-snow** [thymeleaf/thymeleaf-spring#227]
Following https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-mvc-static-content it should be enough to add

```
spring.resources.chain.enabled=true
spring.resources.chain.strategy.content.enabled=true
spring.resources.chain.strategy.content.paths=/**
```

to my `application.properties` in order to enable the cache busting / fingerprinting of my static assets.

Here's an example thymeleaf doc head:

```html
<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org">
<head>
    <meta charset="utf-8">
    <title th:text="#{page.title}"></title>
    <link th:href="@{/css/main.css}" rel="stylesheet" media="screen"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
```

However, the output is still `/css/main.css` without any version.

Spring Boot v2.2.6.RELEASE  
id 'org.springframework.boot' version '2.2.6.RELEASE'
id 'io.spring.dependency-management' version '1.0.9.RELEASE'  
implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

Also running in the IDEA / running the build jar makes no difference.

**Comment by ultraq** [comment]
I was able to get it working by taking the example app downloadable from https://spring.io/guides/gs/serving-web-content/, matching the versions of the dependencies you listed, then adding an `application.properties` file with the config values in your post, adding `<link rel="stylesheet" th:href="@{/css/test.css}"/>` to the `greeting.html` file, and adding an empty CSS file in the `src/main/resources/static/css` directory.  Result:

```html
<!DOCTYPE HTML>
<html>
<head> 
    <title>Getting Started: Serving Web Content</title> 
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" href="/css/test-d41d8cd98f00b204e9800998ecf8427e.css"/>
</head>
<body>
    <p >Hello, World!</p>
</body>
</html>
```

One thing I noticed: if there was no file at the target path (like after I got it working I deleted `test.css`), then Spring Boot couldn't fingerprint my file and I'd get the plain `/css/test.css` in the HTML from the server.  So it might be good to double check paths to resources are correct as that seems to be a requirement for getting it working too.

But the fingerprinting is definitely working with Thymeleaf, so if there are more configuration issues then it might be worth asking over on the Spring Boot GitHub or on StackOverflow with the spring-boot tag.

**Comment by black-snow** [comment]
@ultraq Thanks for looking into this!

There's one more step in my project, we use `sass` and have a `compileSass` step:

*build.gradle*
```groovy
sass {
    version = '1.26.3'
    directory = file("${rootDir}/.gradle/sass")
    baseUrl = 'https://github.com/sass/dart-sass/releases/download'
}

compileSass {
    outputDir = project.file("${buildDir}/resources/main/static/css")
    sourceDir = project.file("${projectDir}/src/main/resources/sass")
    // ... style sourceMap etc.
}

// ...

tasks.bootRun.dependsOn(compileSass)
```

Any chance you can expand your setup and double check this?

As you can see the sass sources are in in `resources/sass`.

**Comment by ultraq** [comment]
Given the configuration options, I'm guessing you used this Gradle plugin: https://github.com/EtienneMiret/sass-gradle-plugin  I took your config and added an empty `test.scss` file to `src/main/resources/sass` which is the source directory pointed to by your config.

After running `gradle bootRun`, I found it didn't create a `test.css` file to overwrite the one that I had working yesterday.  Looking at your config, it's outputting the compiled CSS files to the build directory instead of the source directory where Spring Boot expects to find static resources, so I changed the following:

```
outputDir = project.file("${projectDir}/src/main/resources/static/css")
```

After trying that for a bit, I also found that changes to the Sass file weren't reflected on the server the next time I ran `gradle bootRun` (it was always a change behind).  `bootRun` looks to use the results of compiling your files and processing resources, so I changed the following as well so that changes to Sass files would be included with the next `bootRun`:

```
processResources.dependsOn(compileSass)
```

---
Thinking some more about this, I'm not entirely sure why your original config didn't work for me.  The end result of your config and my changes seems the same in that the CSS file ends up in the same place, but Spring Boot might be doing something that isn't picking up the CSS file unless it exists in the source directory? 🤷‍♂️

**Comment by black-snow** [comment]
@ultraq Thanks a ton for going down the rabbit hole! Sadly, it's still not working even if I let sass compile to the source dir. But let's put sass aside - it's also not working for my javascript resources. And those are not getting transpiled. I have a js-file in `src/main/resources/static/js/` and I use it in a template like this

```xml
<script th:src="@{js/my.js}"></script>
```

But the output is:
```xml
<script src="js/my.js"></script>
```

Tried `/**` and `/js/**` for `spring.resources.chain.strategy.content.paths`. There must be some very stupid mistake in my setup. Here's most of my `build.gradle`:

```groovy
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.google.cloud.tools:appengine-gradle-plugin:2.2.0'
    }
}

plugins {
    id 'org.springframework.boot' version '2.2.6.RELEASE'
    id 'io.spring.dependency-management' version '1.0.9.RELEASE'
    id 'java'
    id 'io.miret.etienne.sass' version '1.1.1'
}

apply plugin: 'com.google.cloud.tools.appengine'

group = 'a.b'
def versionString = 'dev'
version = versionString
sourceCompatibility = '11'
targetCompatibility = '11'

configurations {
    developmentOnly
    runtimeClasspath {
        extendsFrom developmentOnly
    }
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    maven {
        url 'https://maven-central.storage.googleapis.com'
    }
    jcenter()
    mavenCentral()
}

ext {
    set('springCloudVersion', "Hoxton.SR3")
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-elasticsearch'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.session:spring-session-core'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.session:spring-session-data-redis'
    implementation 'org.springframework.cloud:spring-cloud-gcp-starter-storage'
    implementation 'org.bouncycastle:bcprov-jdk15on:1.65'

    compileOnly 'org.projectlombok:lombok'

    //runtimeOnly 'org.springframework.boot:spring-boot-devtools'

    annotationProcessor 'org.projectlombok:lombok'

    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
    }
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

test {
    //useJUnitPlatform()
}

appengine {
    deploy {
        // left out
    }
}

tasks.appengineDeploy.dependsOn(compileSass)
tasks.processResources.dependsOn(compileSass)

sass {
    // dart-sass version to use:
    version = '1.26.3'

    // Directory where to install dart-sass:
    directory = file("${rootDir}/.gradle/sass")

    // Base URL where to download dart-sass from:
    baseUrl = 'https://github.com/sass/dart-sass/releases/download'
}

compileSass {
    outputDir = project.file("${projectDir}/src/main/resources/static/css")
    sourceDir = project.file("${projectDir}/src/main/resources/sass")
    style = compressed
    noCharset()
    noErrorCss()
    sourceMap = file
    sourceMapUrls = relative
}

bootJar {
    excludeDevtools = true
}

processResources.doLast {
   // some replacements happen here
    ant.replace(
            file: "build/resources/main/application.properties",
            // ...
    )
}
```

**Comment by ultraq** [comment]
I tried getting the content hash stuff working for the JS code, so I put a `my.js` file into the directory you mentioned and when I copied exactly what you had it didn't work:

```html
<script th:src="@{js/my.js}"></script>
```

But when I added a leading `/` it worked:

```html
<script th:src="@{/js/my.js}"></script>
```

Since I was trying to base it all off the https://spring.io/guides/gs/serving-web-content/ example, the URL I was using to hit the template was `localhost:8080/greeting`, so trying to resolve `js/my.js` would have ended up with a path of `localhost:8080/greeting/js/my.js` and there wasn't a file at that path.  But the leading `/` meant to look under `localhost:8080/js/my.js` which maps to the file in the `resources/static/js/my.js`.

Anyway, I have a fork of the example repo with this all working for me that you can check out and compare here: https://github.com/ultraq/gs-serving-web-content/tree/cache-busting-issue/complete  Hoping this all helps some!

**Comment by black-snow** [comment]
@ultraq kudos to you for you efforts - I was finally able to nail the issue down to `lazy-initialization`.

Once I `spring.main.lazy-initialization=true` cache-busting is gone. This seems like a bug to me for the docs say that bean stuff is delayed until an actual HTTP request hits the bean. But it has nothing to do with thymeleaf. I'll open an issue in spring.

Thanks!
