### ISSUE TITLE
Bootstrap Checkbox Disappearing

### ISSUE THREAD

**Issue by bailejl** [thymeleaf/thymeleaf-spring#29]
I am trying to use Bootstrap with Thymeleaf in Spring and I am having a bit of a problem.  I prototyped the page up and got it working, then moved it over to Spring to finish the details.  It all works, except the checkbox disappears and does not show up in the HTML in the browser.  I am using the basic guidelines for a checkbox in Bootstrap, which are here:
http://getbootstrap.com/css/#forms-example

You will notices that the checkbox, input of type checkbox is with a label element.  I don't know if that is causing problems, but I have no errors showing up in the server logs and I am on debug.  Any thoughts?

**Comment by danielfernandez** [comment]
Could you show a snippet of your code? This could happen if you were, for example, including your `<input>` element inside your `<label>` and then applying a processor like `th:text` to your `<label>`:

``` html
<label th:text="${mytext}">...<input type="text" th:field="*{name}" /></label>
```

Because that `th:text` would substitute all the content inside the `<label>`, which is precisely its function. In such case you would need something like and additional span:

``` html
<label><span th:text="${mytext}">...</span><input type="text" th:field="*{name}" /></label>
```

But anyway, this _input-inside-label_ is not what Bootstrap suggests to do, so it would be better if you showed your code.

**Comment by bailejl** [comment]
I think I was brain dead when I typed this up.  I should have slept on it before I typed up this problem.  It is obvious that is what it is doing.  Here is the code I was referencing on Bootstrap's site:

```
  <div class="checkbox">
    <label>
      <input type="checkbox"> Check me out
    </label>
  </div>
```

Here is what I was using:

```
<label id="lblLegalAcceptance" for="ckbLegalAcceptance" th:text="#{label.LegalAcceptance}">
    <input type="checkbox" name="legalAcceptance" th:field="*{legalAcceptance}" id="ckbLegalAcceptance" value="accepted" tabindex="7" />
    Click the checkbox to accept the terms of use for the site
</label>
```

I moved the input before the label and that works.  I will try your suggestion and see how that works.

Thanks,
Joe

**Comment by danielfernandez** [comment]
Ok. I didn't notice that the input was inside the label in the case of the checkbox. I suggest you to use the additional span element therefore.
