### ISSUE TITLE
SpEL fails since 3.0.15 due to removal of java.lang prefix from StandardTypeLocator

### ISSUE THREAD

**Issue by leccelecce** [thymeleaf/thymeleaf-spring#293]
I recently upgraded to Spring Boot 2.6.7, and picked up an upgrade of Thymeleaf from 3.0.14 to 3.0.15.

Suddenly, the following SpEL in my templates throws an exception:

`T(Math).min...`

Going through a fair bit of debugging, it seems to be related to this commit https://github.com/thymeleaf/thymeleaf-spring/commit/e7c5f4da4e5786622b663cc3d8ff596cb52d4b05, which has removed java.lang as a known prefix in ThymeleafEvaluationContextACLTypeLocator.

I have temporarily fixed this by changing to:

`T(java.lang.Math).min`

However the release notes for 3.0.15 made no reference to needing to do this, and following the suggested link to Github shows a release with...no issues https://github.com/thymeleaf/thymeleaf-spring/milestone/44?closed=1

So I'm just wondering if this was an intended effect or I have another issue somewhere else?

**Comment by danielfernandez** [comment]
This is an effect of the actions taken at thymeleaf/thymeleaf#871. Using `java.lang.Math` instead of `Math` is the correct way to adapt to this.

Also note this was not a modification specific to the `thymeleaf-spring` repository but global to the project so it is listed in the milestone for the core: https://github.com/thymeleaf/thymeleaf/milestone/60?closed=1

**Comment by leccelecce** [comment]
Thank you for confirming
