### ISSUE TITLE
Possible RCE with ThymeLeaf 3.0.15

### ISSUE THREAD

**Issue by harwalan** [thymeleaf/thymeleaf-spring#295]
I am able to produce remote code execution that appears to be enabled by ThymeLeaf version 3.0.15 using spring.  It looks kind of [like this](https://github.com/thymeleaf/thymeleaf-spring/issues/256), but perhaps it helps if I explain the setup.

My app allows the user to customize their own templates.  If a user puts java code in their template the Java is executed.  Here's an example:

`<div th:text="${''.getClass().forName('java' + '.lang' + '.Runtime')}"></div> . `

another example:

`<div th:text="${''.getClass().forName('javax.script.ScriptEngineManager').newInstance().getEngineByName('JavaScript').eval('var p = new java.lang.ProcessBuilder();p.command("bash", "-c", "id"); p.redirectErrorStream(true); var process=p.start(); var inputStreamReader = new java.io.DataInputStream(process.getInputStream());output=inputStreamReader.readLine();')} "></div> . `

In the other case ([referenced above](https://github.com/thymeleaf/thymeleaf-spring/issues/256)), this comment was made:

> Thanks for the report. Although I agree this needs to be addressed, I would not consider this a security vulnerability as such, as this behaviour cannot be provoked from the outside: this is a developer willingly finding a way to bypass a security-oriented restriction by forcing Spring EL's syntax.

Does this comment assume that only a developer has access to the templates?  If yes, I'd like to eliminate the assumption and ask that this be considered a high priority vulnerability.

Thanks!

**Comment by danielfernandez** [comment]
If understand correctly, in this case the _"Remote"_ in RCE would come from the fact that the users of your application can actually develop Thymeleaf templates by themselves using the _Standard_ dialects, and then… _upload them to your server for them to be executed_?

If this is correct, I would definitely say that the vulnerability in this case is _in your application_ and not in Thymeleaf.

Given the type of templates Thymeleaf is meant to serve when using the Standard dialects, which include generic _expressions_ like the ones in Spring EL, I think the scenario you describe is a bit like allowing your users to upload `.class` files to be loaded and executed by the JDK, and then calling that an RCE in the JVM.

Several other template engines allow the inclusion of Java code in them, easiest example would be JSP itself. But I don't think considering this fact an RCE vulnerability in JSP would be correct.

In my opinion, a functionality such as the one you describe in your application would require a different kind of templates — certainly ones that are much more restrictive. You can either do this in Thymeleaf itself by implementing **your own dialect** –which can be as restrictive as you want– and then allow your users to develop templates that use _only_ this dialect... or you can alternatively use a simpler, more restrictive template engine instead of Thymeleaf.


### Now, why is Thymeleaf allowing you to execute this?


Here we have to differentiate your two expressions because they are two very different cases. This is the first one:

```
th:text="${''.getClass().forName('java' + '.lang' + '.Runtime')}"
```

This works simply because you are _obtaining_ the class reference for `java.lang.Runtime`, but you are not doing anything with it. The `java.lang.Runtime` class is blocked, so any attempts to call methods on it will throw an exception. But you are not calling any methods, so this is harmless.

Now for the second expression:

```
th:text="${''.getClass().forName('javax.script.ScriptEngineManager').newInstance()...}"
```

This is allowed simply because `javax.script.ScriptEngineManager` is not a _blocked_ class. I would agree that it should be, given `java.lang.Runtime` is, and I can confirm that it will be added in the next version. But still, considering this a vulnerability would miss the point on _what Thymeleaf protects from_.

It would not be reasonable to expect Thymeleaf to protect from its own template developers, or expect it to contemplate the possibility that templates themselves could be inserted from the outside without validation.

What Thymeleaf protects from is direct, unfiltered user input, like _request parameters_. And for this it implements a _restricted mode_.

Thymeleaf's **restricted execution mode** is applied in general wherever a template might be processing direct, unfiltered user input, such as _request parameters_. This include pre-processing expressions (`__...__`), unescaped output (`th:utext`) and inlined unescaped expressions, links, event handlers, fragment expressions…

But this is not one of those scenarios: first, because it is using `th:text`, which is meant to simply output _escaped_ text; and second and most important, because there is no _direct user input_ involved in this template expression. It is an expression that has been included in the template by the developer him/herself.

So in this case, what you are _bypassing_ with this expression using `javax.script.ScriptEngineManager` is not really the main check, which Thymeleaf imposes on _direct user input_, but an additional restriction introduced in 3.0.15 itself _"for higher security"_: the blocked classes (see thymeleaf/thymeleaf#871). Thymeleaf 3.1 (already in development) will implement a much larger control over what classes can be used in expressions, but Thymeleaf 3.0 simply implements this with a list of blocked classes. After all, this is a _secondary_ check for the sake of peace of mind, and the aim keeps being exclusively to control user input.

And again, a `th:text` with a value like yours is not _user input_, and therefore only the secondary, additional check applies.

\
So my conclusion here is that, for this specific scenario, Thymeleaf _standard_ templates are not the right choice. I would definitely recommend using a custom dialect, or alternatively a different technology.

\
Also, please note that publishing about possible vulnerabilities in public forums before contacting the [project team](https://www.thymeleaf.org/team.html) and discussing the scenario in private creates unnecessary alarm and is, in general, a very bad practice.

**Comment by harwalan** [comment]
@danielfernandez I really appreciate your thorough response!  I also apologize that I used a less preferred method for communicating potential vulnerabilities.  I totally see the reasons behind it. 

I'm already invested in ThymeLeaf and would love to find a way to close off the evaluation of Java inside a template.  Is there a way to do this?  Thanks!

**Comment by danielfernandez** [comment]
> I'm already invested in ThymeLeaf and would love to find a way to close off the evaluation of Java inside a template. Is there a way to do this? Thanks!

You mean that you would like to be able to execute _some_ Java in your templates, but without all what the Standard dialects offer? If so, this would require creating a custom dialect and adding Java execution capabilities to it, perhaps through some expression language (i.e. not SpringEL) that allows for a restricted use of Java code... or else use SpringEL but restrict quite a lot its Java capabilities...
