### ISSUE TITLE
NPE after upgrade from 2.0.19 to 2.1.0

### ISSUE THREAD

**Issue by lukaslisowski** [thymeleaf/thymeleaf-spring#39]
Hey,

after upgrading from Thymeleaf 2.0.19 to 2.1.0 following NPE occurs on  Plesk 11.5.30 Update21 [CentOS 6.4 (Final) / openjdk-1.6.0.0 / tomcat-6.0.24]. On Windows [Win7 (64-Bit) / jdk_1.7.0_45 / tomcat-7.0.42] everything is fine.

<code>java.lang.NullPointerException
    org.thymeleaf.spring3.processor.attr.SpringInputGeneralFieldAttrProcessor.doProcess(SpringInputGeneralFieldAttrProcessor.java:110)
    org.thymeleaf.spring3.processor.attr.AbstractSpringFieldAttrProcessor.processAttribute(AbstractSpringFieldAttrProcessor.java:103)
    org.thymeleaf.processor.attr.AbstractAttrProcessor.doProcess(AbstractAttrProcessor.java:87)
    org.thymeleaf.processor.AbstractProcessor.process(AbstractProcessor.java:212)
    org.thymeleaf.dom.Node.applyNextProcessor(Node.java:973)
    org.thymeleaf.dom.Node.processNode(Node.java:928)
    org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:654)
    org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:637)
    org.thymeleaf.dom.Node.processNode(Node.java:947)
    org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:654)
    org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:637)
</code>

**Comment by danielfernandez** [comment]
This is fixed by thymeleaf/thymeleaf-spring3@9c264fac212e6d80ba68941ee0b43eb63beb66f6 and will be solved in 2.1.1, to be released at the end of the week. It is already fixed in 2.1.1-SNAPSHOT, if you want to try (See http://www.thymeleaf.org/faq.html#use-snapshot).

This happens due to a change in the way BindStatus objects are obtained in 2.1, and might arise if the variable you are binding to is a local variable or you are executing on an offline Spring-enabled environment (like f.e. the testing framework).

**Comment by danielfernandez** [comment]
By the way, it should have no relation to your operating system or Java version... it just depends on your code and the thymeleaf version you are using.
