### ISSUE TITLE
SeedStarter Manager ${{sb.datePlanted}} not format correct

### ISSUE THREAD

**Issue by ghost** [thymeleaf/thymeleaf-spring#43]
I am remove thethymeleafexamples.stsm.web.conversion.DateFormatter from  conversionService  bean config in spring-servlete.xml and use Spring DateTimeFormatAnnotationFormatterFactory instead to do the format work.
@DateTimeFormat(pattern="yyyy-MM-dd")
 private Date datePlanted = null;
but
th:field="*{datePlanted}"   this format ok.
${{sb.datePlanted}}          this not format, why?

**Comment by danielfernandez** [comment]
It's a bit complex :-). I suppose you made that change in this line: https://github.com/thymeleaf/thymeleafexamples-stsm/blob/thymeleafexamples-stsm-20131104/src/main/webapp/WEB-INF/templates/seedstartermng.html#L34

The fact is, conversions in Spring apps can be divided into two categories:
- Those that merely depend on the type of the data to be displayed: Formatters and Converters.
- Those that depend on the existence of a Spring-based `BindingResult` object on the context variable: PropertyEditors and formatting annotations.

The change you made moved the application of the pattern to the date from the first group to the second. And therefore, in order to work, required that the object on which it is applied (the first-level context variable, i.e., in this case, `sb`) had a `BindingResult` associated with it (`BindingResult`s are automatically created by Spring _before_ executing the template on every context object that matches certain criteria: not being a collection, a String, etc.)

The problem is, `sb` wasn't created a `BindingResult` by Spring because it actually isn't a context variable. Instead, it is a local variable created just a couple of lines above, at the `th:each` attribute:

``` html
<tr th:each="sb : ${allSeedStarters}">
```

Because of this, this variable has no `BindingResult` associated with it, and Spring --to which Thymeleaf delegates the `${{...}}` expression-- does not know about any formatting annotations to be applied.

So this is actually the expected behaviour...

**Comment by danielfernandez** [comment]
Related to this, #49 will try to support the `th:each` scenario by creating `BindingResult` objects for the iterated objects.

**Comment by danielfernandez** [comment]
Note this has been implemented and will be a part of Thymeleaf 2.1.3. See #49 for more information.
