### ISSUE TITLE
Migration to thymeleaf 2.1.2 fails for projects using thymeleaf-extras-springsecurityx

### ISSUE THREAD

**Issue by thanasio** [thymeleaf/thymeleaf-spring#45]
I tried to migrate our project to release 2.1.2 artifactId: thymeleaf-spring4. However, as our project uses thymeleaf-extras-springsecurity3 release 2.1.1 and there is no thymeleaf-extras-springsecurity4 release 2.1.2, the project crashes during deplyment as a result of thymeleaf-extras-springsecurity3 dependenies to thymeleaf-spring3 of release 2.1.1 .

Just wanted to raise awareness on the issue!

**Comment by danielfernandez** [comment]
thymeleaf-extras-springsecurity3 version 2.1.1.RELEASE includes Spring 4 support: http://forum.thymeleaf.org/Updated-thymeleaf-extras-springsecurity3-with-Spring-4-support-td4027322.html

Note there is no thymeleaf-extras-springsecurity4 because Spring Security 4 does not exist. The most current version of Spring Security (published just a week ago) is Spring Security 3.2.0. This library is a different project than the Spring Framework, and thus does not follow the same versioning pace as the Framework.
