### ISSUE TITLE
Add MapAccessor to ThymeleafEvaluationContext

### ISSUE THREAD

**Issue by nithril** [thymeleaf/thymeleaf-spring#46]
Hello,

Is it possible to add `org.springframework.context.expression.MapAccessor` accessor to `ThymeleafEvaluationContext` ? Or is there any reason to not have add it ?

Thanks,

**Comment by nithril** [comment]
Can I start to fix it ?

**Comment by danielfernandez** [comment]
I would like to evaluate first the current use of this accessor... is this accessor currently added in the `EvaluationContext` instances used by the Spring JSP TagLibs? what kind of access in Spring EL expressions does it enable?

**Comment by nithril** [comment]
Sorry, wanted to cancel my comment, not closed this issue.

This accessor seems to be used by Spring JSP with `EvalTag`. 

It enables dot notation for Map `map.key`. `VariablesMapPropertyAccessor` is restricted to `VariablesMap` instance

**Comment by danielfernandez** [comment]
Looks good and quite easy:
- Both `ThymeleafEvaluationContext` and `ThymeleafEvaluationContextWrapper` should be modified in order to add this accessor.
- The Spring `MapAccessor` class does not have any kind of state, so both modified classes should benefit from keeping a constant (`private static final`) object of class `MapAccessor` and use this only _singleton_ object at the `addPropertyAccessor(...)` calls.
- Once this is added, the `VariablesMapPropertyAccessor` can probably be removed as the `VariablesMap` class extends `HashMap`.

The reason this wasn't being added in Thymeleaf already is that even if `MapAccessor` appeared in Spring 3.0, it wasn't until 3.1 that it was added to the evaluation context being used for JSP taglibs. And the first implementation of Thymeleaf's evaluation context support was developed by trying to mirror the behaviour of Spring, using version 3.0 as a model.

@nithril would you like to do a pull request for this? If you do, please make sure you read https://github.com/thymeleaf/thymeleaf/blob/thymeleaf-2.1.2.RELEASE/CONTRIBUTING.markdown and take the steps explained there (e.g. write a comment explicitly agreeing to the contribution terms).

Also, it would be great if you could create pull requests for both this "thymeleaf-spring3" repository and the "thymeleaf-spring4" one, both for the `2.0-dev` and `2.1-dev` branches (so that this feature gets added to both 2.0.x and 2.1.x).

**Comment by nithril** [comment]
Prior to PR could you have a look?

**Comment by danielfernandez** [comment]
@nithril looks perfect. I can take care of deleting `VariablesMapAccessor` afterwards.

**Comment by nithril** [comment]
I have create the PRs. I think it is better you take care of VariablesMapAccessor. I do not have enough knowledge of Thymeleaf.

I accept the Thymeleaf Contributing Terms and Conditions including the Thymeleaf Individual Contributor License Agreement.
