### ISSUE TITLE
Default to UTF-8

### ISSUE THREAD

**Issue by amr** [thymeleaf/thymeleaf-spring#47]
I suggest that the documentation for spring integration defaults to setting the resolver's `characterEncoding` property to UTF-8 as this is almost always what the developer wants.

Perhaps the more correct thing to do is to make this the view resolver's default.

**Comment by danielfernandez** [comment]
I agree there is a big amount of developers that want or need to use UTF-8. But Thymeleaf uses ISO-8859-1 in order to provide an easier integration for Spring users, as this encoding is the one used by default in Spring MVC for JSP views: https://github.com/spring-projects/spring-framework/blob/v4.0.0.RELEASE/spring-webmvc/src/main/java/org/springframework/web/servlet/view/AbstractView.java#L59

So we try to apply here the _principle of least surprise_ and not apply a setting which is contrary to the default in all other view technologies used with Spring.
