### ISSUE TITLE
ThymeleafViewResolver accidentally picks up non-view beans

### ISSUE THREAD

**Issue by odrotbohm** [thymeleaf/thymeleaf-spring#65]
Assume the `ApplicationContext` contains an arbitrary bean with the name of a view by accident, `ThymeleafViewResolver.loadView(…)` will attempt to re-initialize the bean which is very likely to fail as the bean definition contains the setup for a completely different type.

So `loadView(…)` needs to double check the bean type and fall back to the view created manually in case the found bean is not an `AbstractThymeleafView`.

**Comment by danielfernandez** [comment]
I'm not completely sure about what you mean... these lines from https://github.com/thymeleaf/thymeleaf-spring/blob/f011dcc0eb751eef1fa05e707cf3006c1aaa62f5/thymeleaf-spring3/src/main/java/org/thymeleaf/spring3/view/ThymeleafViewResolver.java#L644-L649

``` java
    // The AUTOWIRE_NO mode applies autowiring only through annotations
    beanFactory.autowireBeanProperties(view, AutowireCapableBeanFactory.AUTOWIRE_NO, false);
    // A bean with this name exists, so we apply its properties
    beanFactory.applyBeanPropertyValues(view, viewName);
    // Finally, we let Spring do the remaining initializations (incl. proxifying if needed)
    view = (AbstractThymeleafView) beanFactory.initializeBean(view, viewName);
```

Should take care of initializing the `view` object, which will always be an `AbstractThymeleafView` because it comes from https://github.com/thymeleaf/thymeleaf-spring/blob/f011dcc0eb751eef1fa05e707cf3006c1aaa62f5/thymeleaf-spring3/src/main/java/org/thymeleaf/spring3/view/ThymeleafViewResolver.java#L636

``` java
AbstractThymeleafView view = BeanUtils.instantiateClass(getViewClass());
```

So the idea with the lines above is initialize the `view` object by performing any declared autowiring and setting all the properties that might match a different bean declared with the same `viewName` name, used therefore as a sort of prototype be it an `AbstractThymeleafView` instance or not.

But I'm not sure about when the bean with name `viewName` wil get re-initialized or even modified at all there as you say... it should be `view` (a new, recently instanced object) the only one to be modified...

Am I missing or misunderstanding anything there?

**Comment by odrotbohm** [comment]
``` java
            if (viewBeanType != null && AbstractThymeleafView.class.isAssignableFrom(viewBeanType)) {
                view = (AbstractThymeleafView) beanFactory.configureBean(view, viewName);
            } else {
                // The AUTOWIRE_NO mode applies autowiring only through annotations
                beanFactory.autowireBeanProperties(view, AutowireCapableBeanFactory.AUTOWIRE_NO, false);
                // A bean with this name exists, so we apply its properties
                beanFactory.applyBeanPropertyValues(view, viewName);
                // Finally, we let Spring do the remaining initializations (incl. proxifying if needed)
                view = (AbstractThymeleafView) beanFactory.initializeBean(view, viewName);
            }
```

Assume we have a view name `guestbook` and - by accident a Spring Bean in our `applicationContext` of type `Guestbook` which has nothing to do with the view at all but is just an arbitrary service. `applyBeanPropertyValues(…)` will then go ahead an take the property definitions registered for the arbitrary bean and try to apply these to the subtype of `AbstractThymeleafView` will fail if the bean is not assignable to `AbstractThymeleafView` in the first place.

Complete example:

``` java
class Guestbook {

  public void setDependency(…) { … };
}
```

If I now return `guestbook` as view name Thymeleaf will run into the else branch and try to invoke the property binding for `dependency` on the `ThymeleafView` which causes:

```
Error creating bean with name 'guestbook': Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'dependency' of bean class [org.thymeleaf.spring4.view.ThymeleafView]: Bean property 'dependency' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
```

I guess applying properties only makes sense if the bean type is of the view type.

**Comment by odrotbohm** [comment]
I am generally wondering which case the else branch is supposed to catch: a bean definition with the name of the view to resolve but not implementing `AbstractThymeleafView`. Is that a common scenario? I mean, if I want view instantiation and population via Spring, I'd declare the view as a prototype bean in the first place (which let's the if-branch kick in), wouldn't I?

**Comment by danielfernandez** [comment]
Hmmm... the _support_ for initializing the new `View` instance from a non-`View` registered bean is there since the very beginning, in version 1.0.0, but basically by error, because `configureBean()` was being used for every appctx-registered bean be it a `View` or not: https://github.com/thymeleaf/thymeleaf-spring/blob/thymeleaf-spring3-1.1.5/src/main/java/org/thymeleaf/spring3/view/ThymeleafViewResolver.java#L220-L224

The current shape of this code, with calls to `autowireBeanProperties()` and `applyBeanPropertyValues()` when the appctx-registered bean is not a `View` comes from 2.0.19, as a result of fixing #30.

The problem is that this modification in 2.0.19 includes code for processing views by using non-view beans as prototypes, which as you say is a problem. We were probably thinking of using things like mere `Properties` as prototypes, but anyway the fact that `applyBeanPropertyValues` might fail if a property does not exist in the view object makes this clearly a potential problem, we should have checked that scenario. 

I agree with you it's better to protect the case when a registered, non-view bean exists with the same name and simply not use the registered bean as a prototype at all if it is not an `AbstractThymeleafView`.

I will be adding a patch for this soon. Thanks.

**Comment by odrotbohm** [comment]
That's great to hear thanks. It might be a brute force solution but you could add a catch block around the initialization to simply skip it in case it fails. Remembering that decision for further attempts to resolve the view might be a good idea, too.

**Comment by danielfernandez** [comment]
I finally went for an IMHO cleaner approach: allow prototyping of views by means of both registered beans of type `AbstractThymeleafView` and also registered abstract beans (no type). This should cover all scenarios that actually make sense.

In any other cases, beans registered at the Application Context will not be used as prototypes.

Updated 2.1.4-SNAPSHOT

**Comment by danielfernandez** [comment]
Thymeleaf 2.1.4 has just been published, including this fix.

**Comment by odrotbohm** [comment]
Awesome, Daniel, thanks a lot! :)
