### ISSUE TITLE
checkbox problem with admin css styles based on twiter bootsrap 

### ISSUE THREAD

**Issue by lubo08** [thymeleaf/thymeleaf-spring#68]
I bay admin layout based on twitter bootstrap and I'm realy anoyed as im not able checkbox to get working. because thymeleaf add hidden field right after checkbox field. then css styles for covered span which style check not working. 

``` html

<label th:for="${#ids.next('agreement')}" class="label-checkbox">
                            <input th:field="*{agreement}" type="checkbox" />
                            <span class="custom-checkbox info bounceIn animation-delay6"></span>
                            <th:block th:text="#{register.agreement}">I accept the agreement.</th:block>
                        </label>

```

Is there any possibility to stop generate this hidden field or choose manually where this field will be placed? 

as this is added automaticaly after checkbox input , checkbox overlay not working. 

``` html
<input type="hidden" name="_agreement" value="on">
```

**Comment by danielfernandez** [comment]
Unfortunately, this hidden `<input>` is required by Spring MVC. The only way you have to avoid it is to not add a `th:field` attribute to your checkbox and try to make it work using `th:name` and `th:value`... though some other form binding problems might arise.

Spring MVC uses the additional hidden `<input>` to actually determine the existence of the field, its visibility, in order to being able to differentiate when the checkbox hasn't been checked from when the checkbox simply was not there. This is because browsers don't send a form parameter for unchecked checkboxes at all, so there is no way to tell the difference until you do something else (e.g. the hidden input).
