### ISSUE TITLE
checking for "Spring form: global errors" results in NPE (Resolved)

### ISSUE THREAD

**Issue by jasonhendriks** [thymeleaf/thymeleaf-spring#75]
I tried the example given at http://www.thymeleaf.org/doc/tutorials/2.1/thymeleafspring.html#global-errors:

That, is:
    `<div th:if="${#fields.hasGlobalErrors()}">`
and
    `<ul th:if="${#fields.hasErrors('global')}">`

When I add them to my HTML, the page won't even render, nevermind about submitting the form. both examples result in:
`org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "#fields.hasErrors('global')" (search:95)`

The NPE is thrown at `bindStatus.isError()` in `org.thymeleaf.spring3.util.FieldUtils.checkErrors(FieldUtils.java:245)`

I tried this with v2.1.4 and v.2.1.3 and got the same error. Bug or am I doing something wrong?

Yes, the tags are all closed and properly formed. Yes, this code was within a form. Yes, all the other aspects of the form work without the global error check.

**Comment by jasonhendriks** [comment]
I stumbled upon http://stackoverflow.com/questions/22948257/thymeleaf-not-displaying-spring-form-error-messages and realized that `th:object` is needed in a tag preceding ${#field.hasGlobalErrors()}. I didn't need `th:object` for any other part of my html form up to now.

Unfortunately, no mention of `th:object` is made anywhere at the tutorial at http://www.thymeleaf.org/doc/tutorials/2.1/thymeleafspring.html#global-errors, or anywhere else I looked.

Everything's working fine now, not a bug. But for the love of all that's good, please update the doc! :)

**Comment by ultraq** [comment]
*nudge nudge* @danielfernandez

**Comment by jasonhendriks** [comment]
I created http://stackoverflow.com/questions/27881743/spring-thyme-leaf-checking-for-global-errors-results-in-npe/27881806 in case anyone has my same issue.

**Comment by danielfernandez** [comment]
Yes, actually, the `all` and `global` modifiers can only work where there is a Spring form binding in place, which is what `th:object` does. Other field error expressions do work, but those two cannot because they are relative to a specific form bean, and in order to know which `all` or `global` errors you want to show, Spring needs to know the name of the form you want to show these errors for.

I'll add a task to the docs in order to better explain this in 8.2 (_"All errors"_) and 8.3 (_"Global errors"_).
