### ISSUE TITLE
Strange mistake in Thymeleaf replace with variable

### ISSUE THREAD

**Issue by KhArtNJava** [thymeleaf/thymeleaf-spring#77]
I have code:

``` html
<div th:each="annotsField : ${annotsFields}"
  th:with="someVariable='admin/editElementsFromObjects/fragments/templateFor'+${annotsField.type()}+' :: templateFor'+${annotsField.type()}">
  <div th:text="'!!!'+${someVariable}+'!!!'" />
  <!--<div th:replace="${someVariable}"  />-->
  <!--<div th:replace="admin/editElementsFromObjects/fragments/templateForString :: templateForString"  />-->
</div>
```

As you see, this code will print on the page something like `!!!admin/editElementsFromObjects/fragments/templateForString :: templateForString!!!` . OK.

But now we will uncomment code

``` html
<div th:replace="admin/editElementsFromObjects/fragments/templateForString :: templateForString"  />
```

It will include existing template file. OK. Good.

But why when I make code something like

``` html
<div th:each="annotsField : ${annotsFields}"
  th:with="someVariable='admin/editElementsFromObjects/fragments/templateFor'+${annotsField.type()}+' :: templateFor'+${annotsField.type()}">
  <div th:replace="${someVariable}"  />
</div>
```

Then I got exception

```
There was an unexpected error (type=Internal Server Error, status=500).
Error resolving template "admin/editElementsFromObjects/fragments/templateForString :: templateForString", template might not exist or might not be accessible by any of the configured Template Resolvers (admin/editElementsFromObjects/editForm:24)
```

Why it can't be included with code `<div th:replace="${someVariable}"/>` but included OK with code `<div th:replace="admin/editElementsFromObjects/fragments/templateForString :: templateForString"/>` and I don't see error in value of the my variable?..

**Comment by danielfernandez** [comment]
Sorry, but GitHub seems to have garbled all your code :( Could you please edit your post so that code samples can be adequately read?

**Comment by ultraq** [comment]
@danielfernandez, this is GitHub, you can edit his post to reveal the code :P

*edits the original post*

There, better.

**Comment by KhArtNJava** [comment]
Any ideas? :)

**Comment by danielfernandez** [comment]
Actually, that's working as intended. The `th:replace` attribute has several possible syntaxes:
- `templateName` for including a complete template.
- `templateName :: fragmentName` for including only a fragment of a specific template.
- `:: fragmentName` for including a fragment of the same template
- ...and then the variants with parameters, like `templateName (param1, param2)`, etc.

Any of the above elements (`templateName`, `fragmentName`, etc.) can be a Thymeleaf Standard Expression like `${someVariable}`. For example: `th:replace="${someVariable} :: ${someFragment}`". But expressions are not executed before determining the different parts of the `th:replace` syntax. This works in the same way as `th:each`.

So what you are doing is actually calling the `templateName` syntax, and Thymeleaf will consider that your `${someVariable}` determines the name of the template to be included (and the value of your `someVariable` variable does not contain a valid template name).

Actually, even if Thymeleaf Standard Expressions have a preprocessing mode (by using `__${someVariable}__` this will apply only after `th:replace` has splitted its value into parts. And I'd agree that maybe preprocessing could be applied before in order to allow you to do what you intend, so I'm adding this as a possible task for 3.0 at #78
