### ISSUE TITLE
Spring bean is not resolved correctly

### ISSUE THREAD

**Issue by ghost** [thymeleaf/thymeleaf-spring#80]
I have a form like this:

```
<form action="#" th:action="@{/}" th:object="${@input}" method="post">
    <textarea th:field="*{value}"></textarea>
    ...
<form>
```

and a spring bean like this:

```
@Component
@Scope("session")
public class Input {
    private String value;

    // getter/setter ...
}
```

When I request the page I get the following error:

```
java.lang.IllegalStateException: Neither BindingResult nor plain target object for bean name '@input' available as request attribute
        at org.springframework.web.servlet.support.BindStatus.<init>(BindStatus.java:144) ~[spring-webmvc-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at org.thymeleaf.spring4.util.FieldUtils.getBindStatusFromParsedExpression(FieldUtils.java:396) ~[thymeleaf-spring4-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at org.thymeleaf.spring4.util.FieldUtils.getBindStatus(FieldUtils.java:323) ~[thymeleaf-spring4-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at org.thymeleaf.spring4.util.FieldUtils.getBindStatus(FieldUtils.java:289) ~[thymeleaf-spring4-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at org.thymeleaf.spring4.processor.attr.AbstractSpringFieldAttrProcessor.processAttribute(AbstractSpringFieldAttrProcessor.java:98) ~[thymeleaf-spring4-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at org.thymeleaf.processor.attr.AbstractAttrProcessor.doProcess(AbstractAttrProcessor.java:87) ~[thymeleaf-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at org.thymeleaf.processor.AbstractProcessor.process(AbstractProcessor.java:212) ~[thymeleaf-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at org.thymeleaf.dom.Node.applyNextProcessor(Node.java:1017) ~[thymeleaf-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        ...
```

The error occurs when thymeleaf tries to handle the expression `*{value}`. I can see that when I set a debugging breakpoint in the class `BindStatus` at line 144:

```
Object target = requestContext.getModelObject(beanName);
if (target == null) {
    throw new IllegalStateException(...); // BREAK POINT HERE
}
```

`path` is set to `@input.value`
`beanName` is set to `@input`
`this.expression` is set to `value`

[Here](http://www.thymeleaf.org/doc/tutorials/2.1/thymeleafspring.html) (see 2 The SpringStandard Dialect) is documented that the code above should be working:
- Use Spring Expression Language (Spring EL) as a variable expression language, instead of OGNL. Consequently, all `${...}` and `*{...}` expressions will be evaluated by Spring’s Expression Language engine.
- Access any beans in your application context using SpringEL’s syntax: `${@myBean.doSomething()}`
- New attributes for form processing: `th:field`, `th:errors` and `th:errorclass`, besides a new implementation of `th:object` that allows it to be used for form command selection.

Even this is not working:

```
<form action="#" th:action="@{/}" method="post">
    <textarea th:field="${@input.value}"></textarea>
    ...
<form>
```

I am using spring boot with `ThymeleafAutoConfiguration` enabled. That means the `org.thymeleaf.spring4.dialect.SpringStandardDialect` is active.

**Comment by MatthewEdge** [comment]
I am running into the same issue with two separate projects I'm toying with. One was literally a carbon copy of the example project on spring.io. Both fail with the same exception

**Comment by mehanika** [comment]
I think spring is trying to find the id **input**, if you the declare your bean in a spring xml and assign the id input i will work, or assign the id input to your annotations

**Comment by ghost** [comment]
> I think spring is trying to find the id input, if you the declare your bean in a spring xml and assign the id input i will work, or assign the id input to your annotations

The bean `input` exists in the spring application context, beacause its annotated with `@Component`! But thymeleaf is unable to find/access it.

**Comment by hunzai** [comment]
any news on this - I am getting same error

**Comment by hunzai** [comment]
In my case the problem was ${@input}  , it should be ${input}. I am assuming you have added input as model attribute in your controller.

**Comment by danielfernandez** [comment]
This is a SpringMVC thing, Thymeleaf has little to do with it. And I'll explain:

Your scenario is a bit complicated from the Spring perspective. The following things happen:
- You are using a session bean that is actually maintained by the application context (due to that `@Component`) and not simply by a session-bound controller.
- Spring MVC does not allow the creation of _bindings_ (an internal structure representing methods for reading and writing values on a form bean object) on objects specified as application context beans (`${@input}`) or having more than one level of indirection (`${session.input}`). Form-bound objects must be added to the `model` available to the view (and therefore live as a request attributes or _model attributes_, even if they also exist at the session), and they must be at root level of this model.

There are several ways to do this. See for example http://richardchesterwood.blogspot.com.es/2011/03/using-sessions-in-spring-mvc-including.html

In your case, given I suppose you use `@Component` at your `Input` because you actually need to access it from outside your controller, I'd recommend this approach:
- Set your controller to request-scope, so that a new controller is created for each request.
- Inject your session-scoped `Input` object via good old _auto-wiring_
- Make your session-scoped `Input` available as a model attribute, for instance using `@ModelAttribute`

``` java
@Controller
@Scope("request")
public class MyController {

    @Autowired
    private Input input;

    @ModelAttribute
    public Input input() {
        return this.input;
    }

    @RequestMapping("/")
    public String doThings(final Input input, final BindingResult bindingResult) {
        // The "input" argument and "this.input" will be exactly the same object
        ...
    }

}
```

...and then, given your `input` object is actually a model attribute like any other, you can just use it as `${input}`:

``` html
<form action="#" th:action="@{/}" th:object="${input}" method="post">
    <textarea th:field="*{value}"></textarea>
    ...
<form>
```
