### ISSUE TITLE
redirect: and forward: are not handled correctly

### ISSUE THREAD

**Issue by alan125** [thymeleaf/thymeleaf-spring#81]
In `createView(final String viewName, final Locale locale)`, the first thing done is to call `canHandle(final String viewName, @SuppressWarnings("unused") final Locale locale)`. If the result is false, null is returned. The canHandle method doesn't check if the viewName starts with **redirect:** or **forward:**, so the checks after the call are useless. Either move the the call to the canHandle method to after handling redirect and forward, or add checks to the canHandle method. I prefer the former solution, since the latter will have extra processing overhead.

**Comment by danielfernandez** [comment]
This has also been asked at #94, but I'm not completely sure about it…

I understand the reasons behind it, and from a user's standpoint I would like it to work that way, but the fact is that Spring's `UrlBasedViewResolver` code (used for JSPs) does it in exactly the way it is now, so modifying it would break similarity with how Spring resolves JSPs.

The key thing here is that checking for `redirect:` and `forward:` means actually _resolving_ the template, even if theoretically this view resolver shouldn't be resolving it (because its `viewNames` property don't include any `forward*` or `redirect*` patterns). So we would be resolving something that maybe was reserved for another view resolver further in the resolver chain.

I have to think about it, but if I finally go for modifying this behaviour, I'd possibly add some kind of flag that allows users to modify this mechanism to the way it works right now.

**Comment by danielfernandez** [comment]
This has finally been implemented by adding a new flag to the `ThymeleafViewResolver` classes (both for Spring 3 and Spring 4) called `alwaysProcessRedirectAndForward`.

When `true`, the view resolver will process `redirect:` and `forward:` prefixes _before_ checking the `viewNames` property at the `canHandle(...)` method, and therefore will resolve redirects and forwards without needing to add these prefixes as view name patterns.

When `false` the view resolver will act exactly as it was doing until now (not performing redirects or forwards unless `canHandle()` returns `true`), which is the behaviour found at Spring's `UrlBasedViewResolver` class.

Default value is **`true`**, so this will mean a change in this behaviour between 2.1 and 3.0. But setting this flag to `false` will go back to the old behaviour.

**Comment by danielfernandez** [comment]
Already in `3.0.0-SNAPSHOT`
