### ISSUE TITLE
HTML5Legacy mode forms insert invalid HTML5

### ISSUE THREAD

**Issue by matty** [thymeleaf/thymeleaf-spring#91]
If you use HTML5Legacy mode, using a form with "th:object" to have proper Spring form validation integration causes it to insert invalid HTML5.

e.g
<input id="random" name="randomName" placeholder="" type="text" value="" required=""/>

Note the / is not required and neither is the "" on required="", so it can be just required>

**Comment by danielfernandez** [comment]
This is something that can happen in Thymeleaf 2.1 due to the use of an external tag balancer called _NekoHTML_ in the `LEGACYHTML5` template mode. Unfortunately it is out of the Thymeleaf scope because nekoHTML works separately and previously to Thymeleaf's own parser.

However, Thymeleaf 3.0 has completely revamped its parsing layer (see thymeleaf/thymeleaf#390) so that it does not depend anymore on tag balancers and offers full HTML5 markup support.
