### ISSUE TITLE
Custom formatter not being called in form POST

### ISSUE THREAD

**Issue by alejod** [thymeleaf/thymeleaf-spring#93]
Hi,
I have a dropdown with a list of Country objects coming from the database.
When I submit the form, the binding fails and address.country is null and I get an error "Failed to convert property value of type 'java.lang.String' to required type 'com.myproject.model.Country' for property 'address.country'"

I read about this issue, and everyone using JSP seems to have solved it by adding a custom Formatter or Converter in order to set the "value=" of the <option> tag as a String based on the object's code attribute. 

```
<select class="form-control" th:field="*{address.country}" >
                  <option th:each="country : ${countryList}"
                       th:value="${{country}}" th:text="${country.name}">country name</option>
</select>
```

My custom formatter works fine when it has to show the value in the form:

```
@Override
public String print(Country object, Locale locale) {
    String countryValue = object.getCode();
    return countryValue;
}
```

and it outputs:

```
<select class="form-control" id="address.country" name="address.country">
        <option value="AF">Afghanistan</option>
        <option value="GB" selected="selected">Great Britain</option>
        <option value="MX">Mexico</option>                      
</select>
```

The problem is that the method `parse()` of the formatter is not being called at the time of submit, and I'm still getting the same error. I added a logger and even an exception just to make sure of this and nothing.

```
@Override
public Country parse(String text, Locale locale) throws ParseException {
    logger.info("parse() method in custom formatter");
    throw new ParseException("throwing parse exception", 1);
}
```

Any reason why this won't work? am I missing something?

**Comment by danielfernandez** [comment]
This doesn't look as a Thymeleaf issue. Thymeleaf's responsibility is to actually _render_ your countries as HTML using the formatter, which it is apparently doing alright in your `th:value="${{country}}"` attribute at the `<option>` tag.

The _parsing phase_ of this flow, the part that would have to render your `AF` back into a `Country` object for Afghanistan after form submit, is the responsibility of the Spring MVC controller. Thymeleaf is not executed at all between form submit and controller/formatter execution. So I would say this is a Spring configuration issue. There is probably something lacking in your Spring configuration that is making Spring not really apply formatters to your bound forms (Thymeleaf is, because you are _forcing_ it by using a double-brace expression).
