### ISSUE TITLE
Spring package in distribution causing osgi issues

### ISSUE THREAD

**Issue by garpinc** [thymeleaf/thymeleaf-spring#96]
Is there any need to include org.springframework.web.servlet.tags.form in distribution rather than putting it in a thymeleaf package. When creating osgi manifest: Bundlor Warnings:
    The manifest both imports and exports the package org.springframework.web.servlet.tags.form

This will cause an osgi conflict

**Comment by danielfernandez** [comment]
The reason there is a `org.springframework.web.servlet.tags.form` in the Thymeleaf integration packages is that there are some package-protected classes in Spring at that package that Thymeleaf needs to access. So the only _elegant_ solution is to create `public` wrappers for those classes in that same package in the Thymeleaf distribution in order to publish the needed methods.

I would suggest you to simply exclude that package from any OSGi packages created for thymeleaf, as there is no need to export anything in that package to outside Thymeleaf itself.
